SET NAMES utf8mb4;
SET time_zone = '+00:00';

INSERT INTO `sys_menu`
(`id`, `tenant_id`, `parent_id`, `menu_code`, `menu_name`, `menu_type`, `route_path`, `component_path`,
 `redirect_path`, `icon`, `visible`, `keep_alive`, `external_link`, `permission_mode`, `sort_no`, `status`,
 `version`, `delete_marker`, `create_by`, `create_time`, `update_by`, `update_time`)
VALUES
(1, 1, 0, 'dashboard', 'Dashboard', 'MENU', '/dashboard', 'dashboard/index', NULL, 'dashboard', 1, 1, NULL, 'RELATION', 1, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(10, 1, 0, 'root:system', 'System', 'CATALOG', '/system', NULL, NULL, 'system', 1, 0, NULL, 'RELATION', 10, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(11, 1, 10, 'system:tenant', 'Tenants', 'MENU', '/system/tenant', 'system/tenant/index', NULL, 'tenant', 1, 0, NULL, 'RELATION', 11, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(12, 1, 10, 'system:user', 'Users', 'MENU', '/system/user', 'system/user/index', NULL, 'user', 1, 0, NULL, 'RELATION', 12, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(13, 1, 10, 'system:dept', 'Departments', 'MENU', '/system/dept', 'system/dept/index', NULL, 'dept', 1, 0, NULL, 'RELATION', 13, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(14, 1, 10, 'system:post', 'Posts', 'MENU', '/system/post', 'system/post/index', NULL, 'post', 1, 0, NULL, 'RELATION', 14, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(15, 1, 10, 'system:role', 'Roles', 'MENU', '/system/role', 'system/role/index', NULL, 'role', 1, 0, NULL, 'RELATION', 15, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(16, 1, 10, 'system:menu', 'Menus', 'MENU', '/system/menu', 'system/menu/index', NULL, 'menu', 1, 0, NULL, 'RELATION', 16, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(17, 1, 10, 'system:dict', 'Dictionaries', 'MENU', '/system/dict', 'system/dict/index', NULL, 'dict', 1, 0, NULL, 'RELATION', 17, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(18, 1, 10, 'system:config', 'Configurations', 'MENU', '/system/config', 'system/config/index', NULL, 'config', 1, 0, NULL, 'RELATION', 18, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(19, 1, 10, 'system:notice', 'Notices', 'MENU', '/system/notice', 'system/notice/index', NULL, 'notice', 1, 0, NULL, 'RELATION', 19, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(20, 1, 10, 'system:oauth', 'OAuth Clients', 'MENU', '/system/oauth', 'system/oauth/index', NULL, 'oauth', 1, 0, NULL, 'RELATION', 20, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(21, 1, 10, 'system:social', 'Social Providers', 'MENU', '/system/social', 'system/social/index', NULL, 'social', 1, 0, NULL, 'RELATION', 21, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(22, 1, 10, 'monitor:operlog', 'Operation Logs', 'MENU', '/system/audit/operations', 'system/audit/operations', NULL, 'audit', 1, 0, NULL, 'RELATION', 22, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(23, 1, 10, 'monitor:loginlog', 'Login Logs', 'MENU', '/system/audit/logins', 'system/audit/logins', NULL, 'login-log', 1, 0, NULL, 'RELATION', 23, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(24, 1, 10, 'monitor:online', 'Online Sessions', 'MENU', '/system/sessions', 'system/sessions/index', NULL, 'session', 1, 0, NULL, 'RELATION', 24, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(30, 1, 0, 'structure:definition', 'Structure Intelligence', 'MENU', '/structure-definitions', 'structure/definition/index', NULL, 'schema', 1, 1, NULL, 'RELATION', 30, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(40, 1, 0, 'root:flow', 'Automation', 'CATALOG', '/flows', NULL, NULL, 'flow', 1, 0, NULL, 'RELATION', 40, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(41, 1, 40, 'flow:studio', 'Flow Studio', 'MENU', '/flows/studio', 'flow/studio/index', NULL, 'flow-studio', 1, 1, NULL, 'RELATION', 41, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(42, 1, 40, 'flow:definition', 'Flow Definitions', 'MENU', '/flows/definitions', 'flow/definition/index', NULL, 'flow-definition', 1, 1, NULL, 'RELATION', 42, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(43, 1, 40, 'flow:component', 'Flow Components', 'MENU', '/flows/components', 'flow/component/index', NULL, 'component', 1, 0, NULL, 'RELATION', 43, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(50, 1, 0, 'root:business', 'Business', 'CATALOG', '/business', NULL, NULL, 'business', 1, 0, NULL, 'RELATION', 50, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(51, 1, 50, 'biz:workflow', 'Workflow', 'MENU', '/workflow', 'workflow/index', NULL, 'workflow', 1, 1, NULL, 'RELATION', 51, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(52, 1, 50, 'biz:pay', 'Payment', 'MENU', '/pay', 'pay/index', NULL, 'pay', 1, 0, NULL, 'RELATION', 52, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(53, 1, 50, 'biz:mp', 'Official Account', 'MENU', '/mp', 'mp/index', NULL, 'mp', 1, 0, NULL, 'RELATION', 53, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(54, 1, 50, 'biz:report', 'Reports', 'MENU', '/report', 'report/index', NULL, 'report', 1, 0, NULL, 'RELATION', 54, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(55, 1, 50, 'biz:mobile', 'Mobile Builder', 'MENU', '/mobile', 'mobile/index', NULL, 'mobile', 1, 0, NULL, 'RELATION', 55, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(60, 1, 0, 'root:monitor', 'Monitor', 'CATALOG', '/monitor', NULL, NULL, 'monitor', 1, 0, NULL, 'RELATION', 60, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(61, 1, 60, 'monitor:server', 'Server Monitor', 'MENU', '/monitor/server', 'monitor/server/index', NULL, 'server', 1, 0, NULL, 'RELATION', 61, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(62, 1, 60, 'monitor:cache', 'Cache Monitor', 'MENU', '/monitor/cache', 'monitor/cache/index', NULL, 'cache', 1, 0, NULL, 'RELATION', 62, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(63, 1, 60, 'monitor:druid', 'Datasource Monitor', 'MENU', '/monitor/druid', 'monitor/druid/index', NULL, 'datasource', 1, 0, NULL, 'RELATION', 63, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(70, 1, 0, 'root:tool', 'Tools', 'CATALOG', '/tool', NULL, NULL, 'tool', 1, 0, NULL, 'RELATION', 70, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(71, 1, 70, 'tool:job', 'Scheduler Jobs', 'MENU', '/tool/jobs', 'tool/job/index', NULL, 'job', 1, 0, NULL, 'RELATION', 71, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(72, 1, 70, 'tool:gen', 'Code Generator', 'MENU', '/tool/gen', 'tool/gen/index', NULL, 'code', 1, 0, NULL, 'RELATION', 72, 'ENABLED', 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);

INSERT INTO `sys_permission`
(`tenant_id`, `permission_code`, `permission_name`, `permission_type`, `resource_type`, `resource_path`, `http_method`,
 `description`, `status`, `sort_no`, `version`, `delete_marker`, `create_by`, `create_time`, `update_by`, `update_time`)
VALUES
(1, 'dashboard:view', 'Dashboard View', 'API', 'HTTP_API', '/api/v1/admin/modules', 'GET', 'View dashboard and modules', 'ENABLED', 1, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:tenant:list', 'Tenant List', 'API', 'HTTP_API', '/api/v1/admin/resources/tenants', 'GET', 'List tenants', 'ENABLED', 10, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:tenant:add', 'Tenant Add', 'API', 'HTTP_API', '/api/v1/admin/resources/tenants', 'POST', 'Create tenants', 'ENABLED', 11, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:tenant:edit', 'Tenant Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/tenants/{id}', 'PUT', 'Update tenants', 'ENABLED', 12, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:tenant:remove', 'Tenant Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/tenants/{id}', 'DELETE', 'Remove tenants', 'ENABLED', 13, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:user:list', 'User List', 'API', 'HTTP_API', '/api/v1/users', 'GET', 'List users', 'ENABLED', 20, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:user:add', 'User Add', 'API', 'HTTP_API', '/api/v1/users', 'POST', 'Create users', 'ENABLED', 21, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:user:edit', 'User Edit', 'API', 'HTTP_API', '/api/v1/users/{id}', 'PUT', 'Update users', 'ENABLED', 22, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:user:remove', 'User Remove', 'API', 'HTTP_API', '/api/v1/users/{id}', 'DELETE', 'Remove users', 'ENABLED', 23, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dept:list', 'Department List', 'API', 'HTTP_API', '/api/v1/admin/resources/depts', 'GET', 'List departments', 'ENABLED', 30, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dept:add', 'Department Add', 'API', 'HTTP_API', '/api/v1/admin/resources/depts', 'POST', 'Create departments', 'ENABLED', 31, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dept:edit', 'Department Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/depts/{id}', 'PUT', 'Update departments', 'ENABLED', 32, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dept:remove', 'Department Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/depts/{id}', 'DELETE', 'Remove departments', 'ENABLED', 33, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:post:list', 'Post List', 'API', 'HTTP_API', '/api/v1/admin/resources/posts', 'GET', 'List posts', 'ENABLED', 40, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:post:add', 'Post Add', 'API', 'HTTP_API', '/api/v1/admin/resources/posts', 'POST', 'Create posts', 'ENABLED', 41, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:post:edit', 'Post Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/posts/{id}', 'PUT', 'Update posts', 'ENABLED', 42, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:post:remove', 'Post Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/posts/{id}', 'DELETE', 'Remove posts', 'ENABLED', 43, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:role:list', 'Role List', 'API', 'HTTP_API', '/api/v1/iam/roles', 'GET', 'List roles', 'ENABLED', 50, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:role:add', 'Role Add', 'API', 'HTTP_API', '/api/v1/admin/resources/roles', 'POST', 'Create roles', 'ENABLED', 51, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:role:edit', 'Role Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/roles/{id}', 'PUT', 'Update roles', 'ENABLED', 52, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:role:remove', 'Role Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/roles/{id}', 'DELETE', 'Remove roles', 'ENABLED', 53, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:role:grant', 'Role Grant', 'API', 'HTTP_API', '/api/v1/iam/roles/{id}/menus', 'PUT', 'Grant role menus', 'ENABLED', 54, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:menu:list', 'Menu List', 'API', 'HTTP_API', '/api/v1/iam/menus', 'GET', 'List menus', 'ENABLED', 60, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:menu:add', 'Menu Add', 'API', 'HTTP_API', '/api/v1/iam/menus', 'POST', 'Create menus', 'ENABLED', 61, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:menu:edit', 'Menu Edit', 'API', 'HTTP_API', '/api/v1/iam/menus/{id}', 'PUT', 'Update menus', 'ENABLED', 62, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:menu:remove', 'Menu Remove', 'API', 'HTTP_API', '/api/v1/iam/menus/{id}', 'DELETE', 'Remove menus', 'ENABLED', 63, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dict:list', 'Dictionary List', 'API', 'HTTP_API', '/api/v1/admin/resources/dict-types', 'GET', 'List dictionaries', 'ENABLED', 70, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dict:add', 'Dictionary Add', 'API', 'HTTP_API', '/api/v1/admin/resources/dict-types', 'POST', 'Create dictionaries', 'ENABLED', 71, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dict:edit', 'Dictionary Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/dict-types/{id}', 'PUT', 'Update dictionaries', 'ENABLED', 72, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:dict:remove', 'Dictionary Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/dict-types/{id}', 'DELETE', 'Remove dictionaries', 'ENABLED', 73, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:config:list', 'Configuration List', 'API', 'HTTP_API', '/api/v1/admin/resources/configs', 'GET', 'List configurations', 'ENABLED', 80, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:config:add', 'Configuration Add', 'API', 'HTTP_API', '/api/v1/admin/resources/configs', 'POST', 'Create configurations', 'ENABLED', 81, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:config:edit', 'Configuration Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/configs/{id}', 'PUT', 'Update configurations', 'ENABLED', 82, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:config:remove', 'Configuration Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/configs/{id}', 'DELETE', 'Remove configurations', 'ENABLED', 83, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:notice:list', 'Notice List', 'API', 'HTTP_API', '/api/v1/admin/resources/notices', 'GET', 'List notices', 'ENABLED', 90, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:notice:add', 'Notice Add', 'API', 'HTTP_API', '/api/v1/admin/resources/notices', 'POST', 'Create notices', 'ENABLED', 91, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:notice:edit', 'Notice Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/notices/{id}', 'PUT', 'Update notices', 'ENABLED', 92, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:notice:remove', 'Notice Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/notices/{id}', 'DELETE', 'Remove notices', 'ENABLED', 93, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:oauth:list', 'OAuth Client List', 'API', 'HTTP_API', '/api/v1/admin/resources/oauth-clients', 'GET', 'List OAuth clients', 'ENABLED', 100, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:oauth:add', 'OAuth Client Add', 'API', 'HTTP_API', '/api/v1/admin/resources/oauth-clients', 'POST', 'Create OAuth clients', 'ENABLED', 101, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:oauth:edit', 'OAuth Client Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/oauth-clients/{id}', 'PUT', 'Update OAuth clients', 'ENABLED', 102, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:oauth:remove', 'OAuth Client Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/oauth-clients/{id}', 'DELETE', 'Remove OAuth clients', 'ENABLED', 103, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:social:list', 'Social Provider List', 'API', 'HTTP_API', '/api/v1/admin/resources/social-providers', 'GET', 'List social providers', 'ENABLED', 110, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:social:add', 'Social Provider Add', 'API', 'HTTP_API', '/api/v1/admin/resources/social-providers', 'POST', 'Create social providers', 'ENABLED', 111, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:social:edit', 'Social Provider Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/social-providers/{id}', 'PUT', 'Update social providers', 'ENABLED', 112, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'system:social:remove', 'Social Provider Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/social-providers/{id}', 'DELETE', 'Remove social providers', 'ENABLED', 113, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:operlog:list', 'Operation Log List', 'API', 'HTTP_API', '/api/v1/admin/resources/oper-logs', 'GET', 'List operation logs', 'ENABLED', 120, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:operlog:remove', 'Operation Log Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/oper-logs/{id}', 'DELETE', 'Remove operation logs', 'ENABLED', 121, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:loginlog:list', 'Login Log List', 'API', 'HTTP_API', '/api/v1/admin/resources/login-logs', 'GET', 'List login logs', 'ENABLED', 122, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:loginlog:remove', 'Login Log Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/login-logs/{id}', 'DELETE', 'Remove login logs', 'ENABLED', 123, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:online:list', 'Online Session List', 'API', 'HTTP_API', '/api/v1/admin/resources/online-sessions', 'GET', 'List online sessions', 'ENABLED', 124, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:online:remove', 'Online Session Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/online-sessions/{id}', 'DELETE', 'Remove online sessions', 'ENABLED', 125, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:server:list', 'Server Monitor View', 'API', 'HTTP_API', '/api/v1/monitor/server', 'GET', 'View server monitor', 'ENABLED', 126, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:cache:list', 'Cache Monitor View', 'API', 'HTTP_API', '/api/v1/monitor/cache', 'GET', 'View cache monitor', 'ENABLED', 127, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'monitor:druid:list', 'Datasource Monitor View', 'API', 'HTTP_API', '/api/v1/monitor/druid', 'GET', 'View datasource monitor', 'ENABLED', 128, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'structure:definition:list', 'Structure Definition List', 'API', 'HTTP_API', '/api/v1/structure-definitions', 'GET', 'List structure definitions', 'ENABLED', 130, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'structure:definition:edit', 'Structure Definition Edit', 'API', 'HTTP_API', '/api/v1/structure-definitions', 'POST', 'Edit structure definitions', 'ENABLED', 131, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'structure:definition:publish', 'Structure Definition Publish', 'API', 'HTTP_API', '/api/v1/structure-definitions/{id}/active-version', 'PUT', 'Publish structure definitions', 'ENABLED', 132, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'flow:studio:list', 'Flow Studio View', 'API', 'HTTP_API', '/api/v1/flows', 'GET', 'View flow studio', 'ENABLED', 140, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'flow:definition:edit', 'Flow Definition Edit', 'API', 'HTTP_API', '/api/v1/flows', 'POST', 'Edit flow definitions', 'ENABLED', 141, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'flow:definition:publish', 'Flow Definition Publish', 'API', 'HTTP_API', '/api/v1/flows/{id}/publish', 'POST', 'Publish flow definitions', 'ENABLED', 142, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'flow:component:edit', 'Flow Component Edit', 'API', 'HTTP_API', '/api/v1/flow/components', 'POST', 'Edit flow components', 'ENABLED', 143, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:workflow:list', 'Workflow List', 'API', 'HTTP_API', '/api/v1/workflow/definitions', 'GET', 'List workflow definitions', 'ENABLED', 150, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:workflow:edit', 'Workflow Edit', 'API', 'HTTP_API', '/api/v1/workflow/definitions', 'POST', 'Edit workflow definitions', 'ENABLED', 151, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:workflow:deploy', 'Workflow Deploy', 'API', 'HTTP_API', '/api/v1/workflow/definitions/{id}/deploy', 'PUT', 'Deploy workflows', 'ENABLED', 152, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:workflow:start', 'Workflow Start', 'API', 'HTTP_API', '/api/v1/workflow/definitions/{id}/instances', 'POST', 'Start workflows', 'ENABLED', 153, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:workflow:todo', 'Workflow Todo', 'API', 'HTTP_API', '/api/v1/workflow/tasks/todo', 'GET', 'View workflow todo tasks', 'ENABLED', 154, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:workflow:approve', 'Workflow Approve', 'API', 'HTTP_API', '/api/v1/workflow/tasks/{id}/approve', 'POST', 'Approve workflow tasks', 'ENABLED', 155, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:pay:list', 'Payment List', 'API', 'HTTP_API', '/api/v1/pay/orders', 'GET', 'List payment data', 'ENABLED', 160, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:pay:edit', 'Payment Edit', 'API', 'HTTP_API', '/api/v1/pay/channels', 'POST', 'Edit payment channels', 'ENABLED', 161, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:pay:order', 'Payment Order', 'API', 'HTTP_API', '/api/v1/pay/orders', 'POST', 'Create payment orders', 'ENABLED', 162, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:pay:notify', 'Payment Notify', 'API', 'HTTP_API', '/api/v1/pay/orders/{orderNo}/notify', 'POST', 'Handle payment notify', 'ENABLED', 163, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:mp:list', 'Official Account List', 'API', 'HTTP_API', '/api/v1/mp/accounts', 'GET', 'List official account data', 'ENABLED', 170, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:mp:edit', 'Official Account Edit', 'API', 'HTTP_API', '/api/v1/mp/accounts', 'POST', 'Edit official account data', 'ENABLED', 171, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:mp:sync', 'Official Account Sync', 'API', 'HTTP_API', '/api/v1/mp/accounts/{accountId}/menus/sync', 'POST', 'Sync official account menus', 'ENABLED', 172, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:report:list', 'Report List', 'API', 'HTTP_API', '/api/v1/report/datasets', 'GET', 'List reports', 'ENABLED', 180, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:report:edit', 'Report Edit', 'API', 'HTTP_API', '/api/v1/report/datasets', 'POST', 'Edit reports', 'ENABLED', 181, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:report:query', 'Report Query', 'API', 'HTTP_API', '/api/v1/report/datasets/{id}/query', 'POST', 'Query reports', 'ENABLED', 182, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:report:export', 'Report Export', 'API', 'HTTP_API', '/api/v1/report/datasets/{id}/export.csv', 'POST', 'Export reports', 'ENABLED', 183, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:mobile:list', 'Mobile Builder List', 'API', 'HTTP_API', '/api/v1/mobile/apps', 'GET', 'List mobile apps', 'ENABLED', 190, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'biz:mobile:edit', 'Mobile Builder Edit', 'API', 'HTTP_API', '/api/v1/mobile/apps', 'POST', 'Edit mobile apps', 'ENABLED', 191, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:job:list', 'Job List', 'API', 'HTTP_API', '/api/v1/admin/resources/jobs', 'GET', 'List jobs', 'ENABLED', 200, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:job:add', 'Job Add', 'API', 'HTTP_API', '/api/v1/admin/resources/jobs', 'POST', 'Create jobs', 'ENABLED', 201, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:job:edit', 'Job Edit', 'API', 'HTTP_API', '/api/v1/tool/jobs/{id}/pause', 'POST', 'Edit jobs', 'ENABLED', 202, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:job:remove', 'Job Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/jobs/{id}', 'DELETE', 'Remove jobs', 'ENABLED', 203, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:job:run', 'Job Run', 'API', 'HTTP_API', '/api/v1/tool/jobs/{id}/run', 'POST', 'Run jobs', 'ENABLED', 204, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:gen:list', 'Code Generator List', 'API', 'HTTP_API', '/api/v1/tool/gen/tables', 'GET', 'List generator tables', 'ENABLED', 210, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:gen:add', 'Code Generator Add', 'API', 'HTTP_API', '/api/v1/admin/resources/gen-tables', 'POST', 'Create generator metadata', 'ENABLED', 211, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:gen:edit', 'Code Generator Edit', 'API', 'HTTP_API', '/api/v1/admin/resources/gen-tables/{id}', 'PUT', 'Edit generator metadata', 'ENABLED', 212, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:gen:remove', 'Code Generator Remove', 'API', 'HTTP_API', '/api/v1/admin/resources/gen-tables/{id}', 'DELETE', 'Remove generator metadata', 'ENABLED', 213, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:gen:import', 'Code Generator Import', 'API', 'HTTP_API', '/api/v1/tool/gen/tables/import', 'POST', 'Import generator tables', 'ENABLED', 214, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP),
(1, 'tool:gen:download', 'Code Generator Download', 'API', 'HTTP_API', '/api/v1/tool/gen/tables/{id}/download', 'GET', 'Download generated code', 'ENABLED', 215, 0, 0, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);

INSERT INTO `sys_menu_permission`
(`tenant_id`, `menu_id`, `permission_id`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT p.`tenant_id`, m.`id`, p.`id`, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP
FROM `sys_permission` p
JOIN `sys_menu` m
  ON m.`tenant_id` = p.`tenant_id`
 AND p.`permission_code` LIKE CONCAT(m.`menu_code`, ':%')
WHERE p.`tenant_id` = 1;

INSERT INTO `sys_role_permission`
(`tenant_id`, `role_id`, `permission_id`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT 1, 1, p.`id`, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP
FROM `sys_permission` p
WHERE p.`tenant_id` = 1;
