package top.kx.heartbeat.infrastructure.persistence.mapper.auth;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthOauthClientDO;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthOauthClientDOExample;

import java.util.List;

public interface AuthOauthClientDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    long countByExample(AuthOauthClientDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int deleteByExample(AuthOauthClientDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int insert(AuthOauthClientDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int insertSelective(AuthOauthClientDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    List<AuthOauthClientDO> selectByExample(AuthOauthClientDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    AuthOauthClientDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AuthOauthClientDO row, @Param("example") AuthOauthClientDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AuthOauthClientDO row, @Param("example") AuthOauthClientDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthOauthClientDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_oauth_client
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthOauthClientDO row);
}