package top.kx.heartbeat.infrastructure.persistence.mapper.auth;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthSocialBindingDO;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthSocialBindingDOExample;

import java.util.List;

public interface AuthSocialBindingDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    long countByExample(AuthSocialBindingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int deleteByExample(AuthSocialBindingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int insert(AuthSocialBindingDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int insertSelective(AuthSocialBindingDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    List<AuthSocialBindingDO> selectByExample(AuthSocialBindingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    AuthSocialBindingDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AuthSocialBindingDO row, @Param("example") AuthSocialBindingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AuthSocialBindingDO row, @Param("example") AuthSocialBindingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthSocialBindingDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_binding
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthSocialBindingDO row);
}