package top.kx.heartbeat.infrastructure.persistence.mapper.auth;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthSocialProviderDO;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthSocialProviderDOExample;

import java.util.List;

public interface AuthSocialProviderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    long countByExample(AuthSocialProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int deleteByExample(AuthSocialProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int insert(AuthSocialProviderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int insertSelective(AuthSocialProviderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    List<AuthSocialProviderDO> selectByExample(AuthSocialProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    AuthSocialProviderDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AuthSocialProviderDO row, @Param("example") AuthSocialProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AuthSocialProviderDO row, @Param("example") AuthSocialProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthSocialProviderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_social_provider
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthSocialProviderDO row);
}