package top.kx.heartbeat.infrastructure.persistence.mapper.auth;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthClientRedirectUriDO;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthClientRedirectUriDOExample;

import java.util.List;

public interface AuthClientRedirectUriDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    long countByExample(AuthClientRedirectUriDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int deleteByExample(AuthClientRedirectUriDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int insert(AuthClientRedirectUriDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int insertSelective(AuthClientRedirectUriDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    List<AuthClientRedirectUriDO> selectByExample(AuthClientRedirectUriDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    AuthClientRedirectUriDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AuthClientRedirectUriDO row, @Param("example") AuthClientRedirectUriDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AuthClientRedirectUriDO row, @Param("example") AuthClientRedirectUriDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthClientRedirectUriDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_redirect_uri
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthClientRedirectUriDO row);
}