package top.kx.heartbeat.infrastructure.persistence.mapper.auth;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthSessionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthSessionDOExample;

import java.util.List;

public interface AuthSessionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    long countByExample(AuthSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int deleteByExample(AuthSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int insert(AuthSessionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int insertSelective(AuthSessionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    List<AuthSessionDO> selectByExample(AuthSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    AuthSessionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthSessionDO record, @Param("example") AuthSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthSessionDO record, @Param("example") AuthSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthSessionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthSessionDO record);
}