package top.kx.heartbeat.infrastructure.persistence.mapper.auth;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthClientGrantDO;
import top.kx.heartbeat.infrastructure.persistence.entity.auth.AuthClientGrantDOExample;

import java.util.List;

public interface AuthClientGrantDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    long countByExample(AuthClientGrantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int deleteByExample(AuthClientGrantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int insert(AuthClientGrantDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int insertSelective(AuthClientGrantDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    List<AuthClientGrantDO> selectByExample(AuthClientGrantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    AuthClientGrantDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AuthClientGrantDO row, @Param("example") AuthClientGrantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AuthClientGrantDO row, @Param("example") AuthClientGrantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthClientGrantDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_grant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthClientGrantDO row);
}