package top.kx.heartbeat.infrastructure.persistence.entity.workflow;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wf_process_definition
 */
public class WfProcessDefinitionDO {
    /**
     * Database Column Remarks:
     *   审批流程定义ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   流程名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   流程定义键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.definition_key
     *
     * @mbg.generated
     */
    private String definitionKey;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.version_no
     *
     * @mbg.generated
     */
    private Integer versionNo;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   部署时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.deployed_at
     *
     * @mbg.generated
     */
    private Date deployedAt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * Database Column Remarks:
     *   表单Schema
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_process_definition.form_schema
     *
     * @mbg.generated
     */
    private String formSchema;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.id
     *
     * @return the value of wf_process_definition.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.id
     *
     * @param id the value for wf_process_definition.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.tenant_id
     *
     * @return the value of wf_process_definition.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.tenant_id
     *
     * @param tenantId the value for wf_process_definition.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.name
     *
     * @return the value of wf_process_definition.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.name
     *
     * @param name the value for wf_process_definition.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.definition_key
     *
     * @return the value of wf_process_definition.definition_key
     *
     * @mbg.generated
     */
    public String getDefinitionKey() {
        return definitionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.definition_key
     *
     * @param definitionKey the value for wf_process_definition.definition_key
     *
     * @mbg.generated
     */
    public void setDefinitionKey(String definitionKey) {
        this.definitionKey = definitionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.version_no
     *
     * @return the value of wf_process_definition.version_no
     *
     * @mbg.generated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.version_no
     *
     * @param versionNo the value for wf_process_definition.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.status
     *
     * @return the value of wf_process_definition.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.status
     *
     * @param status the value for wf_process_definition.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.deployed_at
     *
     * @return the value of wf_process_definition.deployed_at
     *
     * @mbg.generated
     */
    public Date getDeployedAt() {
        return deployedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.deployed_at
     *
     * @param deployedAt the value for wf_process_definition.deployed_at
     *
     * @mbg.generated
     */
    public void setDeployedAt(Date deployedAt) {
        this.deployedAt = deployedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.create_time
     *
     * @return the value of wf_process_definition.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.create_time
     *
     * @param createTime the value for wf_process_definition.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.update_time
     *
     * @return the value of wf_process_definition.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.update_time
     *
     * @param updateTime the value for wf_process_definition.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.create_by
     *
     * @return the value of wf_process_definition.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.create_by
     *
     * @param createBy the value for wf_process_definition.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.update_by
     *
     * @return the value of wf_process_definition.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.update_by
     *
     * @param updateBy the value for wf_process_definition.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_process_definition.form_schema
     *
     * @return the value of wf_process_definition.form_schema
     *
     * @mbg.generated
     */
    public String getFormSchema() {
        return formSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_process_definition.form_schema
     *
     * @param formSchema the value for wf_process_definition.form_schema
     *
     * @mbg.generated
     */
    public void setFormSchema(String formSchema) {
        this.formSchema = formSchema;
    }
}