package top.kx.heartbeat.infrastructure.persistence.entity.workflow;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wf_task
 */
public class WfTaskDO {
    /**
     * Database Column Remarks:
     *   审批任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   流程实例ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.instance_id
     *
     * @mbg.generated
     */
    private Long instanceId;

    /**
     * Database Column Remarks:
     *   任务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   处理人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.assignee_id
     *
     * @mbg.generated
     */
    private Long assigneeId;

    /**
     * Database Column Remarks:
     *   任务状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   任务备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.completed_at
     *
     * @mbg.generated
     */
    private Date completedAt;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_task.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.id
     *
     * @return the value of wf_task.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.id
     *
     * @param id the value for wf_task.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.tenant_id
     *
     * @return the value of wf_task.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.tenant_id
     *
     * @param tenantId the value for wf_task.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.instance_id
     *
     * @return the value of wf_task.instance_id
     *
     * @mbg.generated
     */
    public Long getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.instance_id
     *
     * @param instanceId the value for wf_task.instance_id
     *
     * @mbg.generated
     */
    public void setInstanceId(Long instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.name
     *
     * @return the value of wf_task.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.name
     *
     * @param name the value for wf_task.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.assignee_id
     *
     * @return the value of wf_task.assignee_id
     *
     * @mbg.generated
     */
    public Long getAssigneeId() {
        return assigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.assignee_id
     *
     * @param assigneeId the value for wf_task.assignee_id
     *
     * @mbg.generated
     */
    public void setAssigneeId(Long assigneeId) {
        this.assigneeId = assigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.status
     *
     * @return the value of wf_task.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.status
     *
     * @param status the value for wf_task.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.comment
     *
     * @return the value of wf_task.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.comment
     *
     * @param comment the value for wf_task.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.create_time
     *
     * @return the value of wf_task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.create_time
     *
     * @param createTime the value for wf_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.completed_at
     *
     * @return the value of wf_task.completed_at
     *
     * @mbg.generated
     */
    public Date getCompletedAt() {
        return completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.completed_at
     *
     * @param completedAt the value for wf_task.completed_at
     *
     * @mbg.generated
     */
    public void setCompletedAt(Date completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.update_time
     *
     * @return the value of wf_task.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.update_time
     *
     * @param updateTime the value for wf_task.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.create_by
     *
     * @return the value of wf_task.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.create_by
     *
     * @param createBy the value for wf_task.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_task.update_by
     *
     * @return the value of wf_task.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_task.update_by
     *
     * @param updateBy the value for wf_task.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}