package top.kx.heartbeat.infrastructure.persistence.entity.event;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_inbox_event
 */
public class SysInboxEventDO {
    /**
     * Database Column Remarks:
     *   入站事件ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   消费者编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.consumer_code
     *
     * @mbg.generated
     */
    private String consumerCode;

    /**
     * Database Column Remarks:
     *   事件ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.event_id
     *
     * @mbg.generated
     */
    private String eventId;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   处理时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.processed_at
     *
     * @mbg.generated
     */
    private Date processedAt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_inbox_event.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.id
     *
     * @return the value of sys_inbox_event.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.id
     *
     * @param id the value for sys_inbox_event.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.tenant_id
     *
     * @return the value of sys_inbox_event.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.tenant_id
     *
     * @param tenantId the value for sys_inbox_event.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.consumer_code
     *
     * @return the value of sys_inbox_event.consumer_code
     *
     * @mbg.generated
     */
    public String getConsumerCode() {
        return consumerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.consumer_code
     *
     * @param consumerCode the value for sys_inbox_event.consumer_code
     *
     * @mbg.generated
     */
    public void setConsumerCode(String consumerCode) {
        this.consumerCode = consumerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.event_id
     *
     * @return the value of sys_inbox_event.event_id
     *
     * @mbg.generated
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.event_id
     *
     * @param eventId the value for sys_inbox_event.event_id
     *
     * @mbg.generated
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.status
     *
     * @return the value of sys_inbox_event.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.status
     *
     * @param status the value for sys_inbox_event.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.processed_at
     *
     * @return the value of sys_inbox_event.processed_at
     *
     * @mbg.generated
     */
    public Date getProcessedAt() {
        return processedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.processed_at
     *
     * @param processedAt the value for sys_inbox_event.processed_at
     *
     * @mbg.generated
     */
    public void setProcessedAt(Date processedAt) {
        this.processedAt = processedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.create_time
     *
     * @return the value of sys_inbox_event.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.create_time
     *
     * @param createTime the value for sys_inbox_event.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.update_time
     *
     * @return the value of sys_inbox_event.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.update_time
     *
     * @param updateTime the value for sys_inbox_event.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.create_by
     *
     * @return the value of sys_inbox_event.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.create_by
     *
     * @param createBy the value for sys_inbox_event.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_inbox_event.update_by
     *
     * @return the value of sys_inbox_event.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_inbox_event.update_by
     *
     * @param updateBy the value for sys_inbox_event.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}