package top.kx.heartbeat.infrastructure.persistence.entity.mobile;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mobile_page
 */
public class MobilePageDO {
    /**
     * Database Column Remarks:
     *   移动页面ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   移动应用ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.app_id
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     * Database Column Remarks:
     *   页面名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   页面标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.page_key
     *
     * @mbg.generated
     */
    private String pageKey;

    /**
     * Database Column Remarks:
     *   路由路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.route_path
     *
     * @mbg.generated
     */
    private String routePath;

    /**
     * Database Column Remarks:
     *   排序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.sort_no
     *
     * @mbg.generated
     */
    private Integer sortNo;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   页面Schema
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_page.schema_json
     *
     * @mbg.generated
     */
    private String schemaJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.id
     *
     * @return the value of mobile_page.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.id
     *
     * @param id the value for mobile_page.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.tenant_id
     *
     * @return the value of mobile_page.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.tenant_id
     *
     * @param tenantId the value for mobile_page.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.app_id
     *
     * @return the value of mobile_page.app_id
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.app_id
     *
     * @param appId the value for mobile_page.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.name
     *
     * @return the value of mobile_page.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.name
     *
     * @param name the value for mobile_page.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.page_key
     *
     * @return the value of mobile_page.page_key
     *
     * @mbg.generated
     */
    public String getPageKey() {
        return pageKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.page_key
     *
     * @param pageKey the value for mobile_page.page_key
     *
     * @mbg.generated
     */
    public void setPageKey(String pageKey) {
        this.pageKey = pageKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.route_path
     *
     * @return the value of mobile_page.route_path
     *
     * @mbg.generated
     */
    public String getRoutePath() {
        return routePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.route_path
     *
     * @param routePath the value for mobile_page.route_path
     *
     * @mbg.generated
     */
    public void setRoutePath(String routePath) {
        this.routePath = routePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.sort_no
     *
     * @return the value of mobile_page.sort_no
     *
     * @mbg.generated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.sort_no
     *
     * @param sortNo the value for mobile_page.sort_no
     *
     * @mbg.generated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.status
     *
     * @return the value of mobile_page.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.status
     *
     * @param status the value for mobile_page.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.create_time
     *
     * @return the value of mobile_page.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.create_time
     *
     * @param createTime the value for mobile_page.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.update_time
     *
     * @return the value of mobile_page.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.update_time
     *
     * @param updateTime the value for mobile_page.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.create_by
     *
     * @return the value of mobile_page.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.create_by
     *
     * @param createBy the value for mobile_page.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.update_by
     *
     * @return the value of mobile_page.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.update_by
     *
     * @param updateBy the value for mobile_page.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_page.schema_json
     *
     * @return the value of mobile_page.schema_json
     *
     * @mbg.generated
     */
    public String getSchemaJson() {
        return schemaJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_page.schema_json
     *
     * @param schemaJson the value for mobile_page.schema_json
     *
     * @mbg.generated
     */
    public void setSchemaJson(String schemaJson) {
        this.schemaJson = schemaJson;
    }
}
