package top.kx.heartbeat.infrastructure.persistence.entity.mobile;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mobile_app_version
 */
public class MobileAppVersionDO {
    /**
     * Database Column Remarks:
     *   移动应用版本ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   移动应用ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.app_id
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.version_no
     *
     * @mbg.generated
     */
    private Integer versionNo;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.published_at
     *
     * @mbg.generated
     */
    private Date publishedAt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * Database Column Remarks:
     *   应用Schema
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_app_version.schema_json
     *
     * @mbg.generated
     */
    private String schemaJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.id
     *
     * @return the value of mobile_app_version.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.id
     *
     * @param id the value for mobile_app_version.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.tenant_id
     *
     * @return the value of mobile_app_version.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.tenant_id
     *
     * @param tenantId the value for mobile_app_version.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.app_id
     *
     * @return the value of mobile_app_version.app_id
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.app_id
     *
     * @param appId the value for mobile_app_version.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.version_no
     *
     * @return the value of mobile_app_version.version_no
     *
     * @mbg.generated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.version_no
     *
     * @param versionNo the value for mobile_app_version.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.status
     *
     * @return the value of mobile_app_version.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.status
     *
     * @param status the value for mobile_app_version.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.published_at
     *
     * @return the value of mobile_app_version.published_at
     *
     * @mbg.generated
     */
    public Date getPublishedAt() {
        return publishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.published_at
     *
     * @param publishedAt the value for mobile_app_version.published_at
     *
     * @mbg.generated
     */
    public void setPublishedAt(Date publishedAt) {
        this.publishedAt = publishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.create_time
     *
     * @return the value of mobile_app_version.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.create_time
     *
     * @param createTime the value for mobile_app_version.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.update_time
     *
     * @return the value of mobile_app_version.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.update_time
     *
     * @param updateTime the value for mobile_app_version.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.create_by
     *
     * @return the value of mobile_app_version.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.create_by
     *
     * @param createBy the value for mobile_app_version.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.update_by
     *
     * @return the value of mobile_app_version.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.update_by
     *
     * @param updateBy the value for mobile_app_version.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_app_version.schema_json
     *
     * @return the value of mobile_app_version.schema_json
     *
     * @mbg.generated
     */
    public String getSchemaJson() {
        return schemaJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_app_version.schema_json
     *
     * @param schemaJson the value for mobile_app_version.schema_json
     *
     * @mbg.generated
     */
    public void setSchemaJson(String schemaJson) {
        this.schemaJson = schemaJson;
    }
}