package top.kx.heartbeat.infrastructure.persistence.mapper.workflow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.workflow.WfProcessDefinitionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.workflow.WfProcessDefinitionDOExample;

import java.util.List;

public interface WfProcessDefinitionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    long countByExample(WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int deleteByExample(WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int insert(WfProcessDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int insertSelective(WfProcessDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    List<WfProcessDefinitionDO> selectByExampleWithBLOBs(WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    List<WfProcessDefinitionDO> selectByExample(WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    WfProcessDefinitionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") WfProcessDefinitionDO row, @Param("example") WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") WfProcessDefinitionDO row, @Param("example") WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") WfProcessDefinitionDO row, @Param("example") WfProcessDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WfProcessDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(WfProcessDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_process_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WfProcessDefinitionDO row);
}