package top.kx.heartbeat.infrastructure.persistence.mapper.workflow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.workflow.WfTaskActionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.workflow.WfTaskActionDOExample;

import java.util.List;

public interface WfTaskActionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    long countByExample(WfTaskActionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int deleteByExample(WfTaskActionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int insert(WfTaskActionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int insertSelective(WfTaskActionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    List<WfTaskActionDO> selectByExample(WfTaskActionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    WfTaskActionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") WfTaskActionDO row, @Param("example") WfTaskActionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") WfTaskActionDO row, @Param("example") WfTaskActionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WfTaskActionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_task_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WfTaskActionDO row);
}