apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heartbeat-web
  namespace: heartbeat
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: heartbeat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heartbeat-web
                port:
                  number: 80
