apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-secret
  namespace: heartbeat
type: Opaque
stringData:
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "change-me"
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""
  ROCKETMQ_ACCESS_KEY: ""
  ROCKETMQ_SECRET_KEY: ""
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  JWT_SECRET: "change-me-to-a-strong-32-bytes-min-secret"
  CLASSFINAL_PASSWORD: ""
