package top.kx.heartbeat.infrastructure.persistence.mapper.mp;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpAccountDO;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpAccountDOExample;

import java.util.List;

public interface MpAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    long countByExample(MpAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int deleteByExample(MpAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int insert(MpAccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int insertSelective(MpAccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    List<MpAccountDO> selectByExample(MpAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    MpAccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MpAccountDO row, @Param("example") MpAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MpAccountDO row, @Param("example") MpAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MpAccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MpAccountDO row);
}