package top.kx.heartbeat.infrastructure.persistence.mapper.mp;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpAutoReplyDO;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpAutoReplyDOExample;

import java.util.List;

public interface MpAutoReplyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    long countByExample(MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int deleteByExample(MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int insert(MpAutoReplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int insertSelective(MpAutoReplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    List<MpAutoReplyDO> selectByExampleWithBLOBs(MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    List<MpAutoReplyDO> selectByExample(MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    MpAutoReplyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MpAutoReplyDO row, @Param("example") MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") MpAutoReplyDO row, @Param("example") MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MpAutoReplyDO row, @Param("example") MpAutoReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MpAutoReplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MpAutoReplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_auto_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MpAutoReplyDO row);
}