package top.kx.heartbeat.infrastructure.persistence.mapper.mp;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpMenuDO;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpMenuDOExample;

import java.util.List;

public interface MpMenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    long countByExample(MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int deleteByExample(MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int insert(MpMenuDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int insertSelective(MpMenuDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    List<MpMenuDO> selectByExampleWithBLOBs(MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    List<MpMenuDO> selectByExample(MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    MpMenuDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MpMenuDO row, @Param("example") MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") MpMenuDO row, @Param("example") MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MpMenuDO row, @Param("example") MpMenuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MpMenuDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MpMenuDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MpMenuDO row);
}