package top.kx.heartbeat.infrastructure.persistence.mapper.mp;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpSyncLogDO;
import top.kx.heartbeat.infrastructure.persistence.entity.mp.MpSyncLogDOExample;

import java.util.List;

public interface MpSyncLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    long countByExample(MpSyncLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int deleteByExample(MpSyncLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int insert(MpSyncLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int insertSelective(MpSyncLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    List<MpSyncLogDO> selectByExample(MpSyncLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    MpSyncLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MpSyncLogDO row, @Param("example") MpSyncLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MpSyncLogDO row, @Param("example") MpSyncLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MpSyncLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MpSyncLogDO row);
}