package top.kx.heartbeat.infrastructure.persistence.entity.flow;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hb_flow_run_event
 */
public class HbFlowRunEventDOWithBLOBs extends HbFlowRunEventDO {
    /**
     * Database Column Remarks:
     *   输入数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_flow_run_event.input_json
     *
     * @mbg.generated
     */
    private String inputJson;

    /**
     * Database Column Remarks:
     *   输出数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_flow_run_event.output_json
     *
     * @mbg.generated
     */
    private String outputJson;

    /**
     * Database Column Remarks:
     *   错误信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_flow_run_event.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_flow_run_event.input_json
     *
     * @return the value of hb_flow_run_event.input_json
     *
     * @mbg.generated
     */
    public String getInputJson() {
        return inputJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_flow_run_event.input_json
     *
     * @param inputJson the value for hb_flow_run_event.input_json
     *
     * @mbg.generated
     */
    public void setInputJson(String inputJson) {
        this.inputJson = inputJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_flow_run_event.output_json
     *
     * @return the value of hb_flow_run_event.output_json
     *
     * @mbg.generated
     */
    public String getOutputJson() {
        return outputJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_flow_run_event.output_json
     *
     * @param outputJson the value for hb_flow_run_event.output_json
     *
     * @mbg.generated
     */
    public void setOutputJson(String outputJson) {
        this.outputJson = outputJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_flow_run_event.error_message
     *
     * @return the value of hb_flow_run_event.error_message
     *
     * @mbg.generated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_flow_run_event.error_message
     *
     * @param errorMessage the value for hb_flow_run_event.error_message
     *
     * @mbg.generated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}