package top.kx.heartbeat.infrastructure.persistence.entity.flow;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hb_flow_version
 */
public class HbFlowVersionDOWithBLOBs extends HbFlowVersionDO {
    /**
     * Database Column Remarks:
     *   流程DSL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_flow_version.dsl_json
     *
     * @mbg.generated
     */
    private String dslJson;

    /**
     * Database Column Remarks:
     *   编译报告
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_flow_version.compile_report
     *
     * @mbg.generated
     */
    private String compileReport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_flow_version.dsl_json
     *
     * @return the value of hb_flow_version.dsl_json
     *
     * @mbg.generated
     */
    public String getDslJson() {
        return dslJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_flow_version.dsl_json
     *
     * @param dslJson the value for hb_flow_version.dsl_json
     *
     * @mbg.generated
     */
    public void setDslJson(String dslJson) {
        this.dslJson = dslJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_flow_version.compile_report
     *
     * @return the value of hb_flow_version.compile_report
     *
     * @mbg.generated
     */
    public String getCompileReport() {
        return compileReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_flow_version.compile_report
     *
     * @param compileReport the value for hb_flow_version.compile_report
     *
     * @mbg.generated
     */
    public void setCompileReport(String compileReport) {
        this.compileReport = compileReport;
    }
}