package top.kx.heartbeat.infrastructure.persistence.mapper.flow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbConnectionCredentialDO;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbConnectionCredentialDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbConnectionCredentialDOWithBLOBs;

import java.util.List;

public interface HbConnectionCredentialDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    long countByExample(HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int deleteByExample(HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int insert(HbConnectionCredentialDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int insertSelective(HbConnectionCredentialDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    List<HbConnectionCredentialDOWithBLOBs> selectByExampleWithBLOBs(HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    List<HbConnectionCredentialDO> selectByExample(HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    HbConnectionCredentialDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") HbConnectionCredentialDOWithBLOBs row, @Param("example") HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") HbConnectionCredentialDOWithBLOBs row, @Param("example") HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") HbConnectionCredentialDO row, @Param("example") HbConnectionCredentialDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HbConnectionCredentialDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HbConnectionCredentialDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_connection_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HbConnectionCredentialDO row);
}