package top.kx.heartbeat.infrastructure.persistence.mapper.flow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowRunDO;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowRunDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowRunDOWithBLOBs;

import java.util.List;

public interface HbFlowRunDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    long countByExample(HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int deleteByExample(HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int insert(HbFlowRunDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int insertSelective(HbFlowRunDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    List<HbFlowRunDOWithBLOBs> selectByExampleWithBLOBs(HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    List<HbFlowRunDO> selectByExample(HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    HbFlowRunDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") HbFlowRunDOWithBLOBs row, @Param("example") HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") HbFlowRunDOWithBLOBs row, @Param("example") HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") HbFlowRunDO row, @Param("example") HbFlowRunDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HbFlowRunDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HbFlowRunDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HbFlowRunDO row);
}