package top.kx.heartbeat.infrastructure.persistence.mapper.flow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowVersionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowVersionDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowVersionDOWithBLOBs;

import java.util.List;

public interface HbFlowVersionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    long countByExample(HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int deleteByExample(HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int insert(HbFlowVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int insertSelective(HbFlowVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    List<HbFlowVersionDOWithBLOBs> selectByExampleWithBLOBs(HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    List<HbFlowVersionDO> selectByExample(HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    HbFlowVersionDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") HbFlowVersionDOWithBLOBs row, @Param("example") HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") HbFlowVersionDOWithBLOBs row, @Param("example") HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") HbFlowVersionDO row, @Param("example") HbFlowVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HbFlowVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HbFlowVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HbFlowVersionDO row);
}