package top.kx.heartbeat.infrastructure.persistence.mapper.flow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowRunEventDO;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowRunEventDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowRunEventDOWithBLOBs;

import java.util.List;

public interface HbFlowRunEventDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    long countByExample(HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int deleteByExample(HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int insert(HbFlowRunEventDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int insertSelective(HbFlowRunEventDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    List<HbFlowRunEventDOWithBLOBs> selectByExampleWithBLOBs(HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    List<HbFlowRunEventDO> selectByExample(HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    HbFlowRunEventDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") HbFlowRunEventDOWithBLOBs row, @Param("example") HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") HbFlowRunEventDOWithBLOBs row, @Param("example") HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") HbFlowRunEventDO row, @Param("example") HbFlowRunEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HbFlowRunEventDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HbFlowRunEventDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_run_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HbFlowRunEventDO row);
}