package top.kx.heartbeat.infrastructure.persistence.mapper.flow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowDefinitionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbFlowDefinitionDOExample;

import java.util.List;

public interface HbFlowDefinitionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    long countByExample(HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int deleteByExample(HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int insert(HbFlowDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int insertSelective(HbFlowDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    List<HbFlowDefinitionDO> selectByExampleWithBLOBs(HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    List<HbFlowDefinitionDO> selectByExample(HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    HbFlowDefinitionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") HbFlowDefinitionDO row, @Param("example") HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") HbFlowDefinitionDO row, @Param("example") HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") HbFlowDefinitionDO row, @Param("example") HbFlowDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HbFlowDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HbFlowDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_flow_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HbFlowDefinitionDO row);
}