package top.kx.heartbeat.infrastructure.persistence.mapper.flow;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbNodeComponentDO;
import top.kx.heartbeat.infrastructure.persistence.entity.flow.HbNodeComponentDOExample;

import java.util.List;

public interface HbNodeComponentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    long countByExample(HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int deleteByExample(HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int insert(HbNodeComponentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int insertSelective(HbNodeComponentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    List<HbNodeComponentDO> selectByExampleWithBLOBs(HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    List<HbNodeComponentDO> selectByExample(HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    HbNodeComponentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") HbNodeComponentDO row, @Param("example") HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") HbNodeComponentDO row, @Param("example") HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") HbNodeComponentDO row, @Param("example") HbNodeComponentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HbNodeComponentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HbNodeComponentDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_node_component
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HbNodeComponentDO row);
}