package top.kx.heartbeat.infrastructure.persistence.entity.auth;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_session
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AuthSessionDO {
    /**
     * Database Column Remarks:
     *   会话记录ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   会话ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.session_id
     *
     * @mbg.generated
     */
    private String sessionId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   访问令牌JTI
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.access_token_jti
     *
     * @mbg.generated
     */
    private String accessTokenJti;

    /**
     * Database Column Remarks:
     *   刷新令牌哈希
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.refresh_token_hash
     *
     * @mbg.generated
     */
    private String refreshTokenHash;

    /**
     * Database Column Remarks:
     *   设备类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.device_type
     *
     * @mbg.generated
     */
    private String deviceType;

    /**
     * Database Column Remarks:
     *   设备名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.device_name
     *
     * @mbg.generated
     */
    private String deviceName;

    /**
     * Database Column Remarks:
     *   登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     * Database Column Remarks:
     *   User-Agent
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.user_agent
     *
     * @mbg.generated
     */
    private String userAgent;

    /**
     * Database Column Remarks:
     *   会话状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   签发时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.issued_at
     *
     * @mbg.generated
     */
    private Date issuedAt;

    /**
     * Database Column Remarks:
     *   访问令牌过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.expire_at
     *
     * @mbg.generated
     */
    private Date expireAt;

    /**
     * Database Column Remarks:
     *   刷新令牌过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.refresh_expire_at
     *
     * @mbg.generated
     */
    private Date refreshExpireAt;

    /**
     * Database Column Remarks:
     *   撤销时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.revoked_at
     *
     * @mbg.generated
     */
    private Date revokedAt;

    /**
     * Database Column Remarks:
     *   最后访问时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.last_access_at
     *
     * @mbg.generated
     */
    private Date lastAccessAt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_session.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.id
     *
     * @return the value of auth_session.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.id
     *
     * @param id the value for auth_session.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.tenant_id
     *
     * @return the value of auth_session.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.tenant_id
     *
     * @param tenantId the value for auth_session.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.session_id
     *
     * @return the value of auth_session.session_id
     *
     * @mbg.generated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.session_id
     *
     * @param sessionId the value for auth_session.session_id
     *
     * @mbg.generated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.user_id
     *
     * @return the value of auth_session.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.user_id
     *
     * @param userId the value for auth_session.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.access_token_jti
     *
     * @return the value of auth_session.access_token_jti
     *
     * @mbg.generated
     */
    public String getAccessTokenJti() {
        return accessTokenJti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.access_token_jti
     *
     * @param accessTokenJti the value for auth_session.access_token_jti
     *
     * @mbg.generated
     */
    public void setAccessTokenJti(String accessTokenJti) {
        this.accessTokenJti = accessTokenJti == null ? null : accessTokenJti.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.refresh_token_hash
     *
     * @return the value of auth_session.refresh_token_hash
     *
     * @mbg.generated
     */
    public String getRefreshTokenHash() {
        return refreshTokenHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.refresh_token_hash
     *
     * @param refreshTokenHash the value for auth_session.refresh_token_hash
     *
     * @mbg.generated
     */
    public void setRefreshTokenHash(String refreshTokenHash) {
        this.refreshTokenHash = refreshTokenHash == null ? null : refreshTokenHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.device_type
     *
     * @return the value of auth_session.device_type
     *
     * @mbg.generated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.device_type
     *
     * @param deviceType the value for auth_session.device_type
     *
     * @mbg.generated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.device_name
     *
     * @return the value of auth_session.device_name
     *
     * @mbg.generated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.device_name
     *
     * @param deviceName the value for auth_session.device_name
     *
     * @mbg.generated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.login_ip
     *
     * @return the value of auth_session.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.login_ip
     *
     * @param loginIp the value for auth_session.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.user_agent
     *
     * @return the value of auth_session.user_agent
     *
     * @mbg.generated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.user_agent
     *
     * @param userAgent the value for auth_session.user_agent
     *
     * @mbg.generated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.status
     *
     * @return the value of auth_session.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.status
     *
     * @param status the value for auth_session.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.issued_at
     *
     * @return the value of auth_session.issued_at
     *
     * @mbg.generated
     */
    public Date getIssuedAt() {
        return issuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.issued_at
     *
     * @param issuedAt the value for auth_session.issued_at
     *
     * @mbg.generated
     */
    public void setIssuedAt(Date issuedAt) {
        this.issuedAt = issuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.expire_at
     *
     * @return the value of auth_session.expire_at
     *
     * @mbg.generated
     */
    public Date getExpireAt() {
        return expireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.expire_at
     *
     * @param expireAt the value for auth_session.expire_at
     *
     * @mbg.generated
     */
    public void setExpireAt(Date expireAt) {
        this.expireAt = expireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.refresh_expire_at
     *
     * @return the value of auth_session.refresh_expire_at
     *
     * @mbg.generated
     */
    public Date getRefreshExpireAt() {
        return refreshExpireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.refresh_expire_at
     *
     * @param refreshExpireAt the value for auth_session.refresh_expire_at
     *
     * @mbg.generated
     */
    public void setRefreshExpireAt(Date refreshExpireAt) {
        this.refreshExpireAt = refreshExpireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.revoked_at
     *
     * @return the value of auth_session.revoked_at
     *
     * @mbg.generated
     */
    public Date getRevokedAt() {
        return revokedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.revoked_at
     *
     * @param revokedAt the value for auth_session.revoked_at
     *
     * @mbg.generated
     */
    public void setRevokedAt(Date revokedAt) {
        this.revokedAt = revokedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.last_access_at
     *
     * @return the value of auth_session.last_access_at
     *
     * @mbg.generated
     */
    public Date getLastAccessAt() {
        return lastAccessAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.last_access_at
     *
     * @param lastAccessAt the value for auth_session.last_access_at
     *
     * @mbg.generated
     */
    public void setLastAccessAt(Date lastAccessAt) {
        this.lastAccessAt = lastAccessAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.create_time
     *
     * @return the value of auth_session.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.create_time
     *
     * @param createTime the value for auth_session.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.update_time
     *
     * @return the value of auth_session.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.update_time
     *
     * @param updateTime the value for auth_session.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.create_by
     *
     * @return the value of auth_session.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.create_by
     *
     * @param createBy the value for auth_session.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_session.update_by
     *
     * @return the value of auth_session.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_session.update_by
     *
     * @param updateBy the value for auth_session.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}