package top.kx.heartbeat.infrastructure.persistence.mapper.event;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.event.FlowWaitStateDO;
import top.kx.heartbeat.infrastructure.persistence.entity.event.FlowWaitStateDOExample;

import java.util.List;

public interface FlowWaitStateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    long countByExample(FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int deleteByExample(FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int insert(FlowWaitStateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int insertSelective(FlowWaitStateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    List<FlowWaitStateDO> selectByExampleWithBLOBs(FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    List<FlowWaitStateDO> selectByExample(FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    FlowWaitStateDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") FlowWaitStateDO row, @Param("example") FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") FlowWaitStateDO row, @Param("example") FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") FlowWaitStateDO row, @Param("example") FlowWaitStateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowWaitStateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowWaitStateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_wait_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowWaitStateDO row);
}