package top.kx.heartbeat.infrastructure.persistence.mapper.event;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.event.SysInboxEventDO;
import top.kx.heartbeat.infrastructure.persistence.entity.event.SysInboxEventDOExample;

import java.util.List;

public interface SysInboxEventDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    long countByExample(SysInboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int deleteByExample(SysInboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int insert(SysInboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int insertSelective(SysInboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    List<SysInboxEventDO> selectByExample(SysInboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    SysInboxEventDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysInboxEventDO row, @Param("example") SysInboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysInboxEventDO row, @Param("example") SysInboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysInboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_inbox_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysInboxEventDO row);
}