package top.kx.heartbeat.infrastructure.persistence.mapper.event;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.event.SysOutboxEventDO;
import top.kx.heartbeat.infrastructure.persistence.entity.event.SysOutboxEventDOExample;

import java.util.List;

public interface SysOutboxEventDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    long countByExample(SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int deleteByExample(SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int insert(SysOutboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int insertSelective(SysOutboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    List<SysOutboxEventDO> selectByExampleWithBLOBs(SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    List<SysOutboxEventDO> selectByExample(SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    SysOutboxEventDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysOutboxEventDO row, @Param("example") SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysOutboxEventDO row, @Param("example") SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysOutboxEventDO row, @Param("example") SysOutboxEventDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOutboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysOutboxEventDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_outbox_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOutboxEventDO row);
}