package top.kx.heartbeat.infrastructure.persistence.entity.pay;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pay_channel
 */
public class PayChannelDO {
    /**
     * Database Column Remarks:
     *   支付渠道ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   渠道名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   支付提供方
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.provider
     *
     * @mbg.generated
     */
    private String provider;

    /**
     * Database Column Remarks:
     *   应用ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     * Database Column Remarks:
     *   应用密钥
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.app_secret
     *
     * @mbg.generated
     */
    private String appSecret;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   排序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.sort_no
     *
     * @mbg.generated
     */
    private Integer sortNo;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * Database Column Remarks:
     *   渠道配置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel.config_json
     *
     * @mbg.generated
     */
    private String configJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.id
     *
     * @return the value of pay_channel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.id
     *
     * @param id the value for pay_channel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.tenant_id
     *
     * @return the value of pay_channel.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.tenant_id
     *
     * @param tenantId the value for pay_channel.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.name
     *
     * @return the value of pay_channel.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.name
     *
     * @param name the value for pay_channel.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.provider
     *
     * @return the value of pay_channel.provider
     *
     * @mbg.generated
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.provider
     *
     * @param provider the value for pay_channel.provider
     *
     * @mbg.generated
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.app_id
     *
     * @return the value of pay_channel.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.app_id
     *
     * @param appId the value for pay_channel.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.app_secret
     *
     * @return the value of pay_channel.app_secret
     *
     * @mbg.generated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.app_secret
     *
     * @param appSecret the value for pay_channel.app_secret
     *
     * @mbg.generated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.status
     *
     * @return the value of pay_channel.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.status
     *
     * @param status the value for pay_channel.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.sort_no
     *
     * @return the value of pay_channel.sort_no
     *
     * @mbg.generated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.sort_no
     *
     * @param sortNo the value for pay_channel.sort_no
     *
     * @mbg.generated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.create_time
     *
     * @return the value of pay_channel.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.create_time
     *
     * @param createTime the value for pay_channel.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.update_time
     *
     * @return the value of pay_channel.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.update_time
     *
     * @param updateTime the value for pay_channel.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.create_by
     *
     * @return the value of pay_channel.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.create_by
     *
     * @param createBy the value for pay_channel.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.update_by
     *
     * @return the value of pay_channel.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.update_by
     *
     * @param updateBy the value for pay_channel.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel.config_json
     *
     * @return the value of pay_channel.config_json
     *
     * @mbg.generated
     */
    public String getConfigJson() {
        return configJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel.config_json
     *
     * @param configJson the value for pay_channel.config_json
     *
     * @mbg.generated
     */
    public void setConfigJson(String configJson) {
        this.configJson = configJson;
    }
}