package top.kx.heartbeat.infrastructure.persistence.entity.pay;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pay_order
 */
public class PayOrderDO {
    /**
     * Database Column Remarks:
     *   支付订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   支付渠道ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.channel_id
     *
     * @mbg.generated
     */
    private Long channelId;

    /**
     * Database Column Remarks:
     *   订单标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * Database Column Remarks:
     *   订单金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   币种
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     * Database Column Remarks:
     *   支付状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   客户端IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.client_ip
     *
     * @mbg.generated
     */
    private String clientIp;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   支付完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.paid_at
     *
     * @mbg.generated
     */
    private Date paidAt;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   扩展信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.extra_json
     *
     * @mbg.generated
     */
    private String extraJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.id
     *
     * @return the value of pay_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.id
     *
     * @param id the value for pay_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.tenant_id
     *
     * @return the value of pay_order.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.tenant_id
     *
     * @param tenantId the value for pay_order.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.order_no
     *
     * @return the value of pay_order.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.order_no
     *
     * @param orderNo the value for pay_order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.channel_id
     *
     * @return the value of pay_order.channel_id
     *
     * @mbg.generated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.channel_id
     *
     * @param channelId the value for pay_order.channel_id
     *
     * @mbg.generated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.subject
     *
     * @return the value of pay_order.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.subject
     *
     * @param subject the value for pay_order.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.amount
     *
     * @return the value of pay_order.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.amount
     *
     * @param amount the value for pay_order.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.currency
     *
     * @return the value of pay_order.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.currency
     *
     * @param currency the value for pay_order.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.status
     *
     * @return the value of pay_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.status
     *
     * @param status the value for pay_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.client_ip
     *
     * @return the value of pay_order.client_ip
     *
     * @mbg.generated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.client_ip
     *
     * @param clientIp the value for pay_order.client_ip
     *
     * @mbg.generated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.create_time
     *
     * @return the value of pay_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.create_time
     *
     * @param createTime the value for pay_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.update_time
     *
     * @return the value of pay_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.update_time
     *
     * @param updateTime the value for pay_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.paid_at
     *
     * @return the value of pay_order.paid_at
     *
     * @mbg.generated
     */
    public Date getPaidAt() {
        return paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.paid_at
     *
     * @param paidAt the value for pay_order.paid_at
     *
     * @mbg.generated
     */
    public void setPaidAt(Date paidAt) {
        this.paidAt = paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.create_by
     *
     * @return the value of pay_order.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.create_by
     *
     * @param createBy the value for pay_order.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.update_by
     *
     * @return the value of pay_order.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.update_by
     *
     * @param updateBy the value for pay_order.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.extra_json
     *
     * @return the value of pay_order.extra_json
     *
     * @mbg.generated
     */
    public String getExtraJson() {
        return extraJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.extra_json
     *
     * @param extraJson the value for pay_order.extra_json
     *
     * @mbg.generated
     */
    public void setExtraJson(String extraJson) {
        this.extraJson = extraJson;
    }
}
