package top.kx.heartbeat.infrastructure.persistence.entity.structure;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table structure_draft
 */
public class StructureDraftDO {
    /**
     * Database Column Remarks:
     *   结构草稿ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   结构定义ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.definition_id
     *
     * @mbg.generated
     */
    private Long definitionId;

    /**
     * Database Column Remarks:
     *   校验模式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.validation_mode
     *
     * @mbg.generated
     */
    private String validationMode;

    /**
     * Database Column Remarks:
     *   样例摘要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.sample_digest
     *
     * @mbg.generated
     */
    private String sampleDigest;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_draft.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.id
     *
     * @return the value of structure_draft.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.id
     *
     * @param id the value for structure_draft.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.tenant_id
     *
     * @return the value of structure_draft.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.tenant_id
     *
     * @param tenantId the value for structure_draft.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.definition_id
     *
     * @return the value of structure_draft.definition_id
     *
     * @mbg.generated
     */
    public Long getDefinitionId() {
        return definitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.definition_id
     *
     * @param definitionId the value for structure_draft.definition_id
     *
     * @mbg.generated
     */
    public void setDefinitionId(Long definitionId) {
        this.definitionId = definitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.validation_mode
     *
     * @return the value of structure_draft.validation_mode
     *
     * @mbg.generated
     */
    public String getValidationMode() {
        return validationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.validation_mode
     *
     * @param validationMode the value for structure_draft.validation_mode
     *
     * @mbg.generated
     */
    public void setValidationMode(String validationMode) {
        this.validationMode = validationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.sample_digest
     *
     * @return the value of structure_draft.sample_digest
     *
     * @mbg.generated
     */
    public String getSampleDigest() {
        return sampleDigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.sample_digest
     *
     * @param sampleDigest the value for structure_draft.sample_digest
     *
     * @mbg.generated
     */
    public void setSampleDigest(String sampleDigest) {
        this.sampleDigest = sampleDigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.update_time
     *
     * @return the value of structure_draft.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.update_time
     *
     * @param updateTime the value for structure_draft.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.create_time
     *
     * @return the value of structure_draft.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.create_time
     *
     * @param createTime the value for structure_draft.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.create_by
     *
     * @return the value of structure_draft.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.create_by
     *
     * @param createBy the value for structure_draft.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_draft.update_by
     *
     * @return the value of structure_draft.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_draft.update_by
     *
     * @param updateBy the value for structure_draft.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}