package top.kx.heartbeat.infrastructure.persistence.entity.structure;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table structure_artifact
 */
public class StructureArtifactDO {
    /**
     * Database Column Remarks:
     *   结构产物ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   结构定义ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.definition_id
     *
     * @mbg.generated
     */
    private Long definitionId;

    /**
     * Database Column Remarks:
     *   结构版本ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.version_id
     *
     * @mbg.generated
     */
    private Long versionId;

    /**
     * Database Column Remarks:
     *   产物类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.artifact_key
     *
     * @mbg.generated
     */
    private String artifactKey;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   产物内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structure_artifact.artifact_json
     *
     * @mbg.generated
     */
    private String artifactJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.id
     *
     * @return the value of structure_artifact.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.id
     *
     * @param id the value for structure_artifact.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.tenant_id
     *
     * @return the value of structure_artifact.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.tenant_id
     *
     * @param tenantId the value for structure_artifact.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.definition_id
     *
     * @return the value of structure_artifact.definition_id
     *
     * @mbg.generated
     */
    public Long getDefinitionId() {
        return definitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.definition_id
     *
     * @param definitionId the value for structure_artifact.definition_id
     *
     * @mbg.generated
     */
    public void setDefinitionId(Long definitionId) {
        this.definitionId = definitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.version_id
     *
     * @return the value of structure_artifact.version_id
     *
     * @mbg.generated
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.version_id
     *
     * @param versionId the value for structure_artifact.version_id
     *
     * @mbg.generated
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.artifact_key
     *
     * @return the value of structure_artifact.artifact_key
     *
     * @mbg.generated
     */
    public String getArtifactKey() {
        return artifactKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.artifact_key
     *
     * @param artifactKey the value for structure_artifact.artifact_key
     *
     * @mbg.generated
     */
    public void setArtifactKey(String artifactKey) {
        this.artifactKey = artifactKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.create_time
     *
     * @return the value of structure_artifact.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.create_time
     *
     * @param createTime the value for structure_artifact.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.update_time
     *
     * @return the value of structure_artifact.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.update_time
     *
     * @param updateTime the value for structure_artifact.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.create_by
     *
     * @return the value of structure_artifact.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.create_by
     *
     * @param createBy the value for structure_artifact.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.update_by
     *
     * @return the value of structure_artifact.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.update_by
     *
     * @param updateBy the value for structure_artifact.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structure_artifact.artifact_json
     *
     * @return the value of structure_artifact.artifact_json
     *
     * @mbg.generated
     */
    public String getArtifactJson() {
        return artifactJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structure_artifact.artifact_json
     *
     * @param artifactJson the value for structure_artifact.artifact_json
     *
     * @mbg.generated
     */
    public void setArtifactJson(String artifactJson) {
        this.artifactJson = artifactJson;
    }
}
