package top.kx.heartbeat.infrastructure.persistence.mapper.structure;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureDefinitionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureDefinitionDOExample;

import java.util.List;

public interface StructureDefinitionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    long countByExample(StructureDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int deleteByExample(StructureDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int insert(StructureDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int insertSelective(StructureDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    List<StructureDefinitionDO> selectByExample(StructureDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    StructureDefinitionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StructureDefinitionDO row, @Param("example") StructureDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StructureDefinitionDO row, @Param("example") StructureDefinitionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StructureDefinitionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_definition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StructureDefinitionDO row);
}