package top.kx.heartbeat.infrastructure.persistence.mapper.structure;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureVersionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureVersionDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureVersionDOWithBLOBs;

import java.util.List;

public interface StructureVersionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    long countByExample(StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int deleteByExample(StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int insert(StructureVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int insertSelective(StructureVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    List<StructureVersionDOWithBLOBs> selectByExampleWithBLOBs(StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    List<StructureVersionDO> selectByExample(StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    StructureVersionDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StructureVersionDOWithBLOBs row, @Param("example") StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") StructureVersionDOWithBLOBs row, @Param("example") StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StructureVersionDO row, @Param("example") StructureVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StructureVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StructureVersionDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StructureVersionDO row);
}