package top.kx.heartbeat.infrastructure.persistence.mapper.structure;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructurePublishAuditDO;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructurePublishAuditDOExample;

import java.util.List;

public interface StructurePublishAuditDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    long countByExample(StructurePublishAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int deleteByExample(StructurePublishAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int insert(StructurePublishAuditDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int insertSelective(StructurePublishAuditDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    List<StructurePublishAuditDO> selectByExample(StructurePublishAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    StructurePublishAuditDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StructurePublishAuditDO row, @Param("example") StructurePublishAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StructurePublishAuditDO row, @Param("example") StructurePublishAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StructurePublishAuditDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_publish_audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StructurePublishAuditDO row);
}