package top.kx.heartbeat.infrastructure.persistence.mapper.structure;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureDraftDO;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureDraftDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.structure.StructureDraftDOWithBLOBs;

import java.util.List;

public interface StructureDraftDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    long countByExample(StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int deleteByExample(StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int insert(StructureDraftDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int insertSelective(StructureDraftDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    List<StructureDraftDOWithBLOBs> selectByExampleWithBLOBs(StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    List<StructureDraftDO> selectByExample(StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    StructureDraftDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StructureDraftDOWithBLOBs row, @Param("example") StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") StructureDraftDOWithBLOBs row, @Param("example") StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StructureDraftDO row, @Param("example") StructureDraftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StructureDraftDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StructureDraftDOWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structure_draft
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StructureDraftDO row);
}