package top.kx.heartbeat.infrastructure.persistence.entity.report;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_query_log
 */
public class ReportQueryLogDO {
    /**
     * Database Column Remarks:
     *   报表查询日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   报表数据集ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.dataset_id
     *
     * @mbg.generated
     */
    private Long datasetId;

    /**
     * Database Column Remarks:
     *   结果行数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.row_count
     *
     * @mbg.generated
     */
    private Integer rowCount;

    /**
     * Database Column Remarks:
     *   查询状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   查询参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_query_log.params_json
     *
     * @mbg.generated
     */
    private String paramsJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.id
     *
     * @return the value of report_query_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.id
     *
     * @param id the value for report_query_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.tenant_id
     *
     * @return the value of report_query_log.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.tenant_id
     *
     * @param tenantId the value for report_query_log.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.dataset_id
     *
     * @return the value of report_query_log.dataset_id
     *
     * @mbg.generated
     */
    public Long getDatasetId() {
        return datasetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.dataset_id
     *
     * @param datasetId the value for report_query_log.dataset_id
     *
     * @mbg.generated
     */
    public void setDatasetId(Long datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.row_count
     *
     * @return the value of report_query_log.row_count
     *
     * @mbg.generated
     */
    public Integer getRowCount() {
        return rowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.row_count
     *
     * @param rowCount the value for report_query_log.row_count
     *
     * @mbg.generated
     */
    public void setRowCount(Integer rowCount) {
        this.rowCount = rowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.status
     *
     * @return the value of report_query_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.status
     *
     * @param status the value for report_query_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.create_time
     *
     * @return the value of report_query_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.create_time
     *
     * @param createTime the value for report_query_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.update_time
     *
     * @return the value of report_query_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.update_time
     *
     * @param updateTime the value for report_query_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.create_by
     *
     * @return the value of report_query_log.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.create_by
     *
     * @param createBy the value for report_query_log.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.update_by
     *
     * @return the value of report_query_log.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.update_by
     *
     * @param updateBy the value for report_query_log.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_query_log.params_json
     *
     * @return the value of report_query_log.params_json
     *
     * @mbg.generated
     */
    public String getParamsJson() {
        return paramsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_query_log.params_json
     *
     * @param paramsJson the value for report_query_log.params_json
     *
     * @mbg.generated
     */
    public void setParamsJson(String paramsJson) {
        this.paramsJson = paramsJson;
    }
}
