package top.kx.heartbeat.infrastructure.persistence.mapper.pay;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayNotifyLogDO;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayNotifyLogDOExample;

import java.util.List;

public interface PayNotifyLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    long countByExample(PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int deleteByExample(PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int insert(PayNotifyLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int insertSelective(PayNotifyLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    List<PayNotifyLogDO> selectByExampleWithBLOBs(PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    List<PayNotifyLogDO> selectByExample(PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    PayNotifyLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PayNotifyLogDO row, @Param("example") PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") PayNotifyLogDO row, @Param("example") PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PayNotifyLogDO row, @Param("example") PayNotifyLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayNotifyLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayNotifyLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayNotifyLogDO row);
}