package top.kx.heartbeat.infrastructure.persistence.mapper.pay;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayOrderDO;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayOrderDOExample;

import java.util.List;

public interface PayOrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    long countByExample(PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int deleteByExample(PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int insert(PayOrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int insertSelective(PayOrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    List<PayOrderDO> selectByExampleWithBLOBs(PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    List<PayOrderDO> selectByExample(PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    PayOrderDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PayOrderDO row, @Param("example") PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") PayOrderDO row, @Param("example") PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PayOrderDO row, @Param("example") PayOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayOrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayOrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayOrderDO row);
}