package top.kx.heartbeat.infrastructure.persistence.mapper.pay;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayRefundDO;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayRefundDOExample;

import java.util.List;

public interface PayRefundDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    long countByExample(PayRefundDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int deleteByExample(PayRefundDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int insert(PayRefundDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int insertSelective(PayRefundDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    List<PayRefundDO> selectByExample(PayRefundDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    PayRefundDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PayRefundDO row, @Param("example") PayRefundDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PayRefundDO row, @Param("example") PayRefundDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayRefundDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayRefundDO row);
}