package top.kx.heartbeat.infrastructure.persistence.mapper.pay;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayTransactionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.pay.PayTransactionDOExample;

import java.util.List;

public interface PayTransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    long countByExample(PayTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int deleteByExample(PayTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int insert(PayTransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int insertSelective(PayTransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    List<PayTransactionDO> selectByExample(PayTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    PayTransactionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PayTransactionDO row, @Param("example") PayTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PayTransactionDO row, @Param("example") PayTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayTransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayTransactionDO row);
}