package top.kx.heartbeat.infrastructure.persistence.entity.sys;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_gen_table
 */
public class SysGenTableDO {
    /**
     * Database Column Remarks:
     *   生成表配置ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   数据库表名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     * Database Column Remarks:
     *   数据库表说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.table_comment
     *
     * @mbg.generated
     */
    private String tableComment;

    /**
     * Database Column Remarks:
     *   生成类名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     * Database Column Remarks:
     *   业务模块名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     * Database Column Remarks:
     *   基础包名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.base_package
     *
     * @mbg.generated
     */
    private String basePackage;

    /**
     * Database Column Remarks:
     *   前端资源标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.resource_key
     *
     * @mbg.generated
     */
    private String resourceKey;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   乐观锁版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   逻辑删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.delete_marker
     *
     * @mbg.generated
     */
    private Long deleteMarker;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   扩展生成选项
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gen_table.options_json
     *
     * @mbg.generated
     */
    private String optionsJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.id
     *
     * @return the value of sys_gen_table.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.id
     *
     * @param id the value for sys_gen_table.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.tenant_id
     *
     * @return the value of sys_gen_table.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.tenant_id
     *
     * @param tenantId the value for sys_gen_table.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.table_name
     *
     * @return the value of sys_gen_table.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.table_name
     *
     * @param tableName the value for sys_gen_table.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.table_comment
     *
     * @return the value of sys_gen_table.table_comment
     *
     * @mbg.generated
     */
    public String getTableComment() {
        return tableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.table_comment
     *
     * @param tableComment the value for sys_gen_table.table_comment
     *
     * @mbg.generated
     */
    public void setTableComment(String tableComment) {
        this.tableComment = tableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.class_name
     *
     * @return the value of sys_gen_table.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.class_name
     *
     * @param className the value for sys_gen_table.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.module_name
     *
     * @return the value of sys_gen_table.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.module_name
     *
     * @param moduleName the value for sys_gen_table.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.base_package
     *
     * @return the value of sys_gen_table.base_package
     *
     * @mbg.generated
     */
    public String getBasePackage() {
        return basePackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.base_package
     *
     * @param basePackage the value for sys_gen_table.base_package
     *
     * @mbg.generated
     */
    public void setBasePackage(String basePackage) {
        this.basePackage = basePackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.resource_key
     *
     * @return the value of sys_gen_table.resource_key
     *
     * @mbg.generated
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.resource_key
     *
     * @param resourceKey the value for sys_gen_table.resource_key
     *
     * @mbg.generated
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.status
     *
     * @return the value of sys_gen_table.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.status
     *
     * @param status the value for sys_gen_table.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.version
     *
     * @return the value of sys_gen_table.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.version
     *
     * @param version the value for sys_gen_table.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.delete_marker
     *
     * @return the value of sys_gen_table.delete_marker
     *
     * @mbg.generated
     */
    public Long getDeleteMarker() {
        return deleteMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.delete_marker
     *
     * @param deleteMarker the value for sys_gen_table.delete_marker
     *
     * @mbg.generated
     */
    public void setDeleteMarker(Long deleteMarker) {
        this.deleteMarker = deleteMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.create_time
     *
     * @return the value of sys_gen_table.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.create_time
     *
     * @param createTime the value for sys_gen_table.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.update_time
     *
     * @return the value of sys_gen_table.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.update_time
     *
     * @param updateTime the value for sys_gen_table.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.create_by
     *
     * @return the value of sys_gen_table.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.create_by
     *
     * @param createBy the value for sys_gen_table.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.update_by
     *
     * @return the value of sys_gen_table.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.update_by
     *
     * @param updateBy the value for sys_gen_table.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gen_table.options_json
     *
     * @return the value of sys_gen_table.options_json
     *
     * @mbg.generated
     */
    public String getOptionsJson() {
        return optionsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gen_table.options_json
     *
     * @param optionsJson the value for sys_gen_table.options_json
     *
     * @mbg.generated
     */
    public void setOptionsJson(String optionsJson) {
        this.optionsJson = optionsJson;
    }
}
