package top.kx.heartbeat.infrastructure.persistence.entity.sys;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_job_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysJobLogDO {
    /**
     * Database Column Remarks:
     *   任务日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.job_id
     *
     * @mbg.generated
     */
    private Long jobId;

    /**
     * Database Column Remarks:
     *   任务编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.job_code
     *
     * @mbg.generated
     */
    private String jobCode;

    /**
     * Database Column Remarks:
     *   调用目标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.invoke_target
     *
     * @mbg.generated
     */
    private String invokeTarget;

    /**
     * Database Column Remarks:
     *   执行结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.result_status
     *
     * @mbg.generated
     */
    private String resultStatus;

    /**
     * Database Column Remarks:
     *   执行消息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * Database Column Remarks:
     *   耗时毫秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.duration_ms
     *
     * @mbg.generated
     */
    private Long durationMs;

    /**
     * Database Column Remarks:
     *   开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.started_at
     *
     * @mbg.generated
     */
    private Date startedAt;

    /**
     * Database Column Remarks:
     *   结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.finished_at
     *
     * @mbg.generated
     */
    private Date finishedAt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.id
     *
     * @return the value of sys_job_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.id
     *
     * @param id the value for sys_job_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.tenant_id
     *
     * @return the value of sys_job_log.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.tenant_id
     *
     * @param tenantId the value for sys_job_log.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.job_id
     *
     * @return the value of sys_job_log.job_id
     *
     * @mbg.generated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.job_id
     *
     * @param jobId the value for sys_job_log.job_id
     *
     * @mbg.generated
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.job_code
     *
     * @return the value of sys_job_log.job_code
     *
     * @mbg.generated
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.job_code
     *
     * @param jobCode the value for sys_job_log.job_code
     *
     * @mbg.generated
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode == null ? null : jobCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.invoke_target
     *
     * @return the value of sys_job_log.invoke_target
     *
     * @mbg.generated
     */
    public String getInvokeTarget() {
        return invokeTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.invoke_target
     *
     * @param invokeTarget the value for sys_job_log.invoke_target
     *
     * @mbg.generated
     */
    public void setInvokeTarget(String invokeTarget) {
        this.invokeTarget = invokeTarget == null ? null : invokeTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.result_status
     *
     * @return the value of sys_job_log.result_status
     *
     * @mbg.generated
     */
    public String getResultStatus() {
        return resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.result_status
     *
     * @param resultStatus the value for sys_job_log.result_status
     *
     * @mbg.generated
     */
    public void setResultStatus(String resultStatus) {
        this.resultStatus = resultStatus == null ? null : resultStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.message
     *
     * @return the value of sys_job_log.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.message
     *
     * @param message the value for sys_job_log.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.duration_ms
     *
     * @return the value of sys_job_log.duration_ms
     *
     * @mbg.generated
     */
    public Long getDurationMs() {
        return durationMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.duration_ms
     *
     * @param durationMs the value for sys_job_log.duration_ms
     *
     * @mbg.generated
     */
    public void setDurationMs(Long durationMs) {
        this.durationMs = durationMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.started_at
     *
     * @return the value of sys_job_log.started_at
     *
     * @mbg.generated
     */
    public Date getStartedAt() {
        return startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.started_at
     *
     * @param startedAt the value for sys_job_log.started_at
     *
     * @mbg.generated
     */
    public void setStartedAt(Date startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.finished_at
     *
     * @return the value of sys_job_log.finished_at
     *
     * @mbg.generated
     */
    public Date getFinishedAt() {
        return finishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.finished_at
     *
     * @param finishedAt the value for sys_job_log.finished_at
     *
     * @mbg.generated
     */
    public void setFinishedAt(Date finishedAt) {
        this.finishedAt = finishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.create_time
     *
     * @return the value of sys_job_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.create_time
     *
     * @param createTime the value for sys_job_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.update_time
     *
     * @return the value of sys_job_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.update_time
     *
     * @param updateTime the value for sys_job_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.create_by
     *
     * @return the value of sys_job_log.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.create_by
     *
     * @param createBy the value for sys_job_log.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.update_by
     *
     * @return the value of sys_job_log.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.update_by
     *
     * @param updateBy the value for sys_job_log.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}