package top.kx.heartbeat.infrastructure.persistence.entity.sys;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_login_log
 */
public class SysLoginLogDO {
    /**
     * Database Column Remarks:
     *   登录日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   链路追踪ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.trace_id
     *
     * @mbg.generated
     */
    private String traceId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   登录类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_type
     *
     * @mbg.generated
     */
    private String loginType;

    /**
     * Database Column Remarks:
     *   登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     * Database Column Remarks:
     *   User-Agent
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.user_agent
     *
     * @mbg.generated
     */
    private String userAgent;

    /**
     * Database Column Remarks:
     *   登录结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.result_status
     *
     * @mbg.generated
     */
    private String resultStatus;

    /**
     * Database Column Remarks:
     *   失败原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.failure_reason
     *
     * @mbg.generated
     */
    private String failureReason;

    /**
     * Database Column Remarks:
     *   登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.logged_at
     *
     * @mbg.generated
     */
    private Date loggedAt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.tenant_id
     *
     * @return the value of sys_login_log.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.tenant_id
     *
     * @param tenantId the value for sys_login_log.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.trace_id
     *
     * @return the value of sys_login_log.trace_id
     *
     * @mbg.generated
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.trace_id
     *
     * @param traceId the value for sys_login_log.trace_id
     *
     * @mbg.generated
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.user_id
     *
     * @return the value of sys_login_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.user_id
     *
     * @param userId the value for sys_login_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.username
     *
     * @return the value of sys_login_log.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.username
     *
     * @param username the value for sys_login_log.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_type
     *
     * @return the value of sys_login_log.login_type
     *
     * @mbg.generated
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_type
     *
     * @param loginType the value for sys_login_log.login_type
     *
     * @mbg.generated
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_ip
     *
     * @return the value of sys_login_log.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_ip
     *
     * @param loginIp the value for sys_login_log.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.user_agent
     *
     * @return the value of sys_login_log.user_agent
     *
     * @mbg.generated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.user_agent
     *
     * @param userAgent the value for sys_login_log.user_agent
     *
     * @mbg.generated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.result_status
     *
     * @return the value of sys_login_log.result_status
     *
     * @mbg.generated
     */
    public String getResultStatus() {
        return resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.result_status
     *
     * @param resultStatus the value for sys_login_log.result_status
     *
     * @mbg.generated
     */
    public void setResultStatus(String resultStatus) {
        this.resultStatus = resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.failure_reason
     *
     * @return the value of sys_login_log.failure_reason
     *
     * @mbg.generated
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.failure_reason
     *
     * @param failureReason the value for sys_login_log.failure_reason
     *
     * @mbg.generated
     */
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.logged_at
     *
     * @return the value of sys_login_log.logged_at
     *
     * @mbg.generated
     */
    public Date getLoggedAt() {
        return loggedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.logged_at
     *
     * @param loggedAt the value for sys_login_log.logged_at
     *
     * @mbg.generated
     */
    public void setLoggedAt(Date loggedAt) {
        this.loggedAt = loggedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.create_time
     *
     * @return the value of sys_login_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.create_time
     *
     * @param createTime the value for sys_login_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.update_time
     *
     * @return the value of sys_login_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.update_time
     *
     * @param updateTime the value for sys_login_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.create_by
     *
     * @return the value of sys_login_log.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.create_by
     *
     * @param createBy the value for sys_login_log.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.update_by
     *
     * @return the value of sys_login_log.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.update_by
     *
     * @param updateBy the value for sys_login_log.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}