package top.kx.heartbeat.infrastructure.persistence.entity.sys;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_notice
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysNoticeDO {
    /**
     * Database Column Remarks:
     *   通知公告ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   公告标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.notice_title
     *
     * @mbg.generated
     */
    private String noticeTitle;

    /**
     * Database Column Remarks:
     *   公告类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.notice_type
     *
     * @mbg.generated
     */
    private String noticeType;

    /**
     * Database Column Remarks:
     *   发布范围
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.publish_scope
     *
     * @mbg.generated
     */
    private String publishScope;

    /**
     * Database Column Remarks:
     *   发布状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.publish_status
     *
     * @mbg.generated
     */
    private String publishStatus;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.published_at
     *
     * @mbg.generated
     */
    private Date publishedAt;

    /**
     * Database Column Remarks:
     *   过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.expired_at
     *
     * @mbg.generated
     */
    private Date expiredAt;

    /**
     * Database Column Remarks:
     *   乐观锁版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   逻辑删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.delete_marker
     *
     * @mbg.generated
     */
    private Long deleteMarker;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   公告内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notice.notice_content
     *
     * @mbg.generated
     */
    private String noticeContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.id
     *
     * @return the value of sys_notice.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.id
     *
     * @param id the value for sys_notice.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.tenant_id
     *
     * @return the value of sys_notice.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.tenant_id
     *
     * @param tenantId the value for sys_notice.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.notice_title
     *
     * @return the value of sys_notice.notice_title
     *
     * @mbg.generated
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.notice_title
     *
     * @param noticeTitle the value for sys_notice.notice_title
     *
     * @mbg.generated
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle == null ? null : noticeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.notice_type
     *
     * @return the value of sys_notice.notice_type
     *
     * @mbg.generated
     */
    public String getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.notice_type
     *
     * @param noticeType the value for sys_notice.notice_type
     *
     * @mbg.generated
     */
    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType == null ? null : noticeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.publish_scope
     *
     * @return the value of sys_notice.publish_scope
     *
     * @mbg.generated
     */
    public String getPublishScope() {
        return publishScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.publish_scope
     *
     * @param publishScope the value for sys_notice.publish_scope
     *
     * @mbg.generated
     */
    public void setPublishScope(String publishScope) {
        this.publishScope = publishScope == null ? null : publishScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.publish_status
     *
     * @return the value of sys_notice.publish_status
     *
     * @mbg.generated
     */
    public String getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.publish_status
     *
     * @param publishStatus the value for sys_notice.publish_status
     *
     * @mbg.generated
     */
    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus == null ? null : publishStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.published_at
     *
     * @return the value of sys_notice.published_at
     *
     * @mbg.generated
     */
    public Date getPublishedAt() {
        return publishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.published_at
     *
     * @param publishedAt the value for sys_notice.published_at
     *
     * @mbg.generated
     */
    public void setPublishedAt(Date publishedAt) {
        this.publishedAt = publishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.expired_at
     *
     * @return the value of sys_notice.expired_at
     *
     * @mbg.generated
     */
    public Date getExpiredAt() {
        return expiredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.expired_at
     *
     * @param expiredAt the value for sys_notice.expired_at
     *
     * @mbg.generated
     */
    public void setExpiredAt(Date expiredAt) {
        this.expiredAt = expiredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.version
     *
     * @return the value of sys_notice.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.version
     *
     * @param version the value for sys_notice.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.delete_marker
     *
     * @return the value of sys_notice.delete_marker
     *
     * @mbg.generated
     */
    public Long getDeleteMarker() {
        return deleteMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.delete_marker
     *
     * @param deleteMarker the value for sys_notice.delete_marker
     *
     * @mbg.generated
     */
    public void setDeleteMarker(Long deleteMarker) {
        this.deleteMarker = deleteMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.create_by
     *
     * @return the value of sys_notice.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.create_by
     *
     * @param createBy the value for sys_notice.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.create_time
     *
     * @return the value of sys_notice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.create_time
     *
     * @param createTime the value for sys_notice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.update_by
     *
     * @return the value of sys_notice.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.update_by
     *
     * @param updateBy the value for sys_notice.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.update_time
     *
     * @return the value of sys_notice.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.update_time
     *
     * @param updateTime the value for sys_notice.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.notice_content
     *
     * @return the value of sys_notice.notice_content
     *
     * @mbg.generated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.notice_content
     *
     * @param noticeContent the value for sys_notice.notice_content
     *
     * @mbg.generated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }
}