package top.kx.heartbeat.infrastructure.persistence.entity.sys;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_post
 */
public class SysPostDO {
    /**
     * Database Column Remarks:
     *   岗位ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   岗位编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     * Database Column Remarks:
     *   岗位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_name
     *
     * @mbg.generated
     */
    private String postName;

    /**
     * Database Column Remarks:
     *   岗位类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_type
     *
     * @mbg.generated
     */
    private String postType;

    /**
     * Database Column Remarks:
     *   岗位说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   排序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.sort_no
     *
     * @mbg.generated
     */
    private Integer sortNo;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   乐观锁版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   逻辑删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.delete_marker
     *
     * @mbg.generated
     */
    private Long deleteMarker;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.id
     *
     * @return the value of sys_post.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.id
     *
     * @param id the value for sys_post.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.tenant_id
     *
     * @return the value of sys_post.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.tenant_id
     *
     * @param tenantId the value for sys_post.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_code
     *
     * @return the value of sys_post.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_code
     *
     * @param postCode the value for sys_post.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_name
     *
     * @return the value of sys_post.post_name
     *
     * @mbg.generated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_name
     *
     * @param postName the value for sys_post.post_name
     *
     * @mbg.generated
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_type
     *
     * @return the value of sys_post.post_type
     *
     * @mbg.generated
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_type
     *
     * @param postType the value for sys_post.post_type
     *
     * @mbg.generated
     */
    public void setPostType(String postType) {
        this.postType = postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.description
     *
     * @return the value of sys_post.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.description
     *
     * @param description the value for sys_post.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.sort_no
     *
     * @return the value of sys_post.sort_no
     *
     * @mbg.generated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.sort_no
     *
     * @param sortNo the value for sys_post.sort_no
     *
     * @mbg.generated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.status
     *
     * @return the value of sys_post.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.status
     *
     * @param status the value for sys_post.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.version
     *
     * @return the value of sys_post.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.version
     *
     * @param version the value for sys_post.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.delete_marker
     *
     * @return the value of sys_post.delete_marker
     *
     * @mbg.generated
     */
    public Long getDeleteMarker() {
        return deleteMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.delete_marker
     *
     * @param deleteMarker the value for sys_post.delete_marker
     *
     * @mbg.generated
     */
    public void setDeleteMarker(Long deleteMarker) {
        this.deleteMarker = deleteMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.create_by
     *
     * @return the value of sys_post.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.create_by
     *
     * @param createBy the value for sys_post.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.create_time
     *
     * @return the value of sys_post.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.create_time
     *
     * @param createTime the value for sys_post.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.update_by
     *
     * @return the value of sys_post.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.update_by
     *
     * @param updateBy the value for sys_post.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.update_time
     *
     * @return the value of sys_post.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.update_time
     *
     * @param updateTime the value for sys_post.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}