package top.kx.heartbeat.infrastructure.persistence.entity.sys;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user_preference
 */
public class SysUserPreferenceDO {
    /**
     * Database Column Remarks:
     *   用户偏好ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   租户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   偏好键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.preference_key
     *
     * @mbg.generated
     */
    private String preferenceKey;

    /**
     * Database Column Remarks:
     *   值类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.value_type
     *
     * @mbg.generated
     */
    private String valueType;

    /**
     * Database Column Remarks:
     *   乐观锁版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   偏好值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_preference.preference_value
     *
     * @mbg.generated
     */
    private String preferenceValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.id
     *
     * @return the value of sys_user_preference.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.id
     *
     * @param id the value for sys_user_preference.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.tenant_id
     *
     * @return the value of sys_user_preference.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.tenant_id
     *
     * @param tenantId the value for sys_user_preference.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.user_id
     *
     * @return the value of sys_user_preference.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.user_id
     *
     * @param userId the value for sys_user_preference.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.preference_key
     *
     * @return the value of sys_user_preference.preference_key
     *
     * @mbg.generated
     */
    public String getPreferenceKey() {
        return preferenceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.preference_key
     *
     * @param preferenceKey the value for sys_user_preference.preference_key
     *
     * @mbg.generated
     */
    public void setPreferenceKey(String preferenceKey) {
        this.preferenceKey = preferenceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.value_type
     *
     * @return the value of sys_user_preference.value_type
     *
     * @mbg.generated
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.value_type
     *
     * @param valueType the value for sys_user_preference.value_type
     *
     * @mbg.generated
     */
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.version
     *
     * @return the value of sys_user_preference.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.version
     *
     * @param version the value for sys_user_preference.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.create_time
     *
     * @return the value of sys_user_preference.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.create_time
     *
     * @param createTime the value for sys_user_preference.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.update_time
     *
     * @return the value of sys_user_preference.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.update_time
     *
     * @param updateTime the value for sys_user_preference.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.create_by
     *
     * @return the value of sys_user_preference.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.create_by
     *
     * @param createBy the value for sys_user_preference.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.update_by
     *
     * @return the value of sys_user_preference.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.update_by
     *
     * @param updateBy the value for sys_user_preference.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_preference.preference_value
     *
     * @return the value of sys_user_preference.preference_value
     *
     * @mbg.generated
     */
    public String getPreferenceValue() {
        return preferenceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_preference.preference_value
     *
     * @param preferenceValue the value for sys_user_preference.preference_value
     *
     * @mbg.generated
     */
    public void setPreferenceValue(String preferenceValue) {
        this.preferenceValue = preferenceValue;
    }
}
