package top.kx.heartbeat.infrastructure.persistence.mapper.report;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.report.ReportDatasetDO;
import top.kx.heartbeat.infrastructure.persistence.entity.report.ReportDatasetDOExample;

import java.util.List;

public interface ReportDatasetDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    long countByExample(ReportDatasetDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int deleteByExample(ReportDatasetDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int insert(ReportDatasetDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int insertSelective(ReportDatasetDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    List<ReportDatasetDO> selectByExample(ReportDatasetDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    ReportDatasetDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ReportDatasetDO row, @Param("example") ReportDatasetDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ReportDatasetDO row, @Param("example") ReportDatasetDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportDatasetDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_dataset
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportDatasetDO row);
}
