package top.kx.heartbeat.infrastructure.persistence.mapper.report;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.report.ReportQueryLogDO;
import top.kx.heartbeat.infrastructure.persistence.entity.report.ReportQueryLogDOExample;

import java.util.List;

public interface ReportQueryLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    long countByExample(ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int deleteByExample(ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int insert(ReportQueryLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int insertSelective(ReportQueryLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    List<ReportQueryLogDO> selectByExampleWithBLOBs(ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    List<ReportQueryLogDO> selectByExample(ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    ReportQueryLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ReportQueryLogDO row, @Param("example") ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") ReportQueryLogDO row, @Param("example") ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ReportQueryLogDO row, @Param("example") ReportQueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportQueryLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ReportQueryLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_query_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportQueryLogDO row);
}