package top.kx.heartbeat.infrastructure.persistence.mapper.report;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.report.ReportTemplateDO;
import top.kx.heartbeat.infrastructure.persistence.entity.report.ReportTemplateDOExample;

import java.util.List;

public interface ReportTemplateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    long countByExample(ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int deleteByExample(ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int insert(ReportTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int insertSelective(ReportTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    List<ReportTemplateDO> selectByExampleWithBLOBs(ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    List<ReportTemplateDO> selectByExample(ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    ReportTemplateDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ReportTemplateDO row, @Param("example") ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") ReportTemplateDO row, @Param("example") ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ReportTemplateDO row, @Param("example") ReportTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ReportTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportTemplateDO row);
}