package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysDictItemDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysDictItemDOExample;

import java.util.List;

public interface SysDictItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    long countByExample(SysDictItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int deleteByExample(SysDictItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int insert(SysDictItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int insertSelective(SysDictItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    List<SysDictItemDO> selectByExample(SysDictItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    SysDictItemDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysDictItemDO row, @Param("example") SysDictItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysDictItemDO row, @Param("example") SysDictItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysDictItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDictItemDO row);
}