package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysDictTypeDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysDictTypeDOExample;

import java.util.List;

public interface SysDictTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    long countByExample(SysDictTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int deleteByExample(SysDictTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int insert(SysDictTypeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int insertSelective(SysDictTypeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    List<SysDictTypeDO> selectByExample(SysDictTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    SysDictTypeDO selectByPrimaryKey(Long dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysDictTypeDO row, @Param("example") SysDictTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysDictTypeDO row, @Param("example") SysDictTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysDictTypeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDictTypeDO row);
}