package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysGenTableDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysGenTableDOExample;

import java.util.List;

public interface SysGenTableDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    long countByExample(SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int deleteByExample(SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int insert(SysGenTableDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int insertSelective(SysGenTableDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    List<SysGenTableDO> selectByExampleWithBLOBs(SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    List<SysGenTableDO> selectByExample(SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    SysGenTableDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysGenTableDO row, @Param("example") SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysGenTableDO row, @Param("example") SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysGenTableDO row, @Param("example") SysGenTableDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysGenTableDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysGenTableDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysGenTableDO row);
}