package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysGenColumnDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysGenColumnDOExample;

import java.util.List;

public interface SysGenColumnDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    long countByExample(SysGenColumnDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int deleteByExample(SysGenColumnDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int insert(SysGenColumnDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int insertSelective(SysGenColumnDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    List<SysGenColumnDO> selectByExample(SysGenColumnDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    SysGenColumnDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysGenColumnDO row, @Param("example") SysGenColumnDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysGenColumnDO row, @Param("example") SysGenColumnDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysGenColumnDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gen_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysGenColumnDO row);
}