package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysJobDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysJobDOExample;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysJobDOKey;

import java.util.List;

public interface SysJobDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    long countByExample(SysJobDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int deleteByExample(SysJobDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SysJobDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insert(SysJobDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insertSelective(SysJobDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    List<SysJobDO> selectByExample(SysJobDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    SysJobDO selectByPrimaryKey(SysJobDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysJobDO row, @Param("example") SysJobDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysJobDO row, @Param("example") SysJobDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysJobDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysJobDO row);
}