package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysMenuPermissionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysMenuPermissionDOExample;

import java.util.List;

public interface SysMenuPermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    long countByExample(SysMenuPermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int deleteByExample(SysMenuPermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int insert(SysMenuPermissionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int insertSelective(SysMenuPermissionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    List<SysMenuPermissionDO> selectByExample(SysMenuPermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    SysMenuPermissionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysMenuPermissionDO row, @Param("example") SysMenuPermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysMenuPermissionDO row, @Param("example") SysMenuPermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysMenuPermissionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMenuPermissionDO row);
}