package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysNoticeDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysNoticeDOExample;

import java.util.List;

public interface SysNoticeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    long countByExample(SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int deleteByExample(SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int insert(SysNoticeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int insertSelective(SysNoticeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    List<SysNoticeDO> selectByExampleWithBLOBs(SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    List<SysNoticeDO> selectByExample(SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    SysNoticeDO selectByPrimaryKey(Integer noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysNoticeDO row, @Param("example") SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysNoticeDO row, @Param("example") SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysNoticeDO row, @Param("example") SysNoticeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysNoticeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysNoticeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysNoticeDO row);
}