package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysOperLogDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysOperLogDOExample;

import java.util.List;

public interface SysOperLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    long countByExample(SysOperLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int deleteByExample(SysOperLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int insert(SysOperLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int insertSelective(SysOperLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    List<SysOperLogDO> selectByExample(SysOperLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    SysOperLogDO selectByPrimaryKey(Long operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysOperLogDO row, @Param("example") SysOperLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysOperLogDO row, @Param("example") SysOperLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOperLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOperLogDO row);
}