package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysPostDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysPostDOExample;

import java.util.List;

public interface SysPostDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    long countByExample(SysPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int deleteByExample(SysPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int insert(SysPostDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int insertSelective(SysPostDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    List<SysPostDO> selectByExample(SysPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysPostDO row, @Param("example") SysPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysPostDO row, @Param("example") SysPostDOExample example);
}