package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysPlanFeatureDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysPlanFeatureDOExample;

import java.util.List;

public interface SysPlanFeatureDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    long countByExample(SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int deleteByExample(SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int insert(SysPlanFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int insertSelective(SysPlanFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    List<SysPlanFeatureDO> selectByExampleWithBLOBs(SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    List<SysPlanFeatureDO> selectByExample(SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    SysPlanFeatureDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysPlanFeatureDO row, @Param("example") SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysPlanFeatureDO row, @Param("example") SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysPlanFeatureDO row, @Param("example") SysPlanFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysPlanFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysPlanFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_plan_feature
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysPlanFeatureDO row);
}