package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysRolePermissionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysRolePermissionDOExample;

import java.util.List;

public interface SysRolePermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    long countByExample(SysRolePermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(SysRolePermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int insert(SysRolePermissionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(SysRolePermissionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    List<SysRolePermissionDO> selectByExample(SysRolePermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    SysRolePermissionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysRolePermissionDO row, @Param("example") SysRolePermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysRolePermissionDO row, @Param("example") SysRolePermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRolePermissionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRolePermissionDO row);
}