package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysTenantDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysTenantDOExample;

import java.util.List;

public interface SysTenantDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    long countByExample(SysTenantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int deleteByExample(SysTenantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int insert(SysTenantDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int insertSelective(SysTenantDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    List<SysTenantDO> selectByExample(SysTenantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    SysTenantDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysTenantDO row, @Param("example") SysTenantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysTenantDO row, @Param("example") SysTenantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysTenantDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysTenantDO row);
}