package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysTenantPlanDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysTenantPlanDOExample;

import java.util.List;

public interface SysTenantPlanDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    long countByExample(SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int deleteByExample(SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int insert(SysTenantPlanDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int insertSelective(SysTenantPlanDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    List<SysTenantPlanDO> selectByExampleWithBLOBs(SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    List<SysTenantPlanDO> selectByExample(SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    SysTenantPlanDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysTenantPlanDO row, @Param("example") SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysTenantPlanDO row, @Param("example") SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysTenantPlanDO row, @Param("example") SysTenantPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysTenantPlanDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysTenantPlanDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysTenantPlanDO row);
}