package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysTenantFeatureDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysTenantFeatureDOExample;

import java.util.List;

public interface SysTenantFeatureDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    long countByExample(SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int deleteByExample(SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int insert(SysTenantFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int insertSelective(SysTenantFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    List<SysTenantFeatureDO> selectByExampleWithBLOBs(SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    List<SysTenantFeatureDO> selectByExample(SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    SysTenantFeatureDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysTenantFeatureDO row, @Param("example") SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysTenantFeatureDO row, @Param("example") SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysTenantFeatureDO row, @Param("example") SysTenantFeatureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysTenantFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysTenantFeatureDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant_feature
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysTenantFeatureDO row);
}