package top.kx.heartbeat.infrastructure.persistence.mapper.sys;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysUserPostDO;
import top.kx.heartbeat.infrastructure.persistence.entity.sys.SysUserPostDOExample;

import java.util.List;

public interface SysUserPostDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    long countByExample(SysUserPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int insert(SysUserPostDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int insertSelective(SysUserPostDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    List<SysUserPostDO> selectByExample(SysUserPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    SysUserPostDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysUserPostDO row, @Param("example") SysUserPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysUserPostDO row, @Param("example") SysUserPostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserPostDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserPostDO row);
}
