package top.kx.heartbeat.infrastructure.persistence.mapper.mobile;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.mobile.MobileAppDO;
import top.kx.heartbeat.infrastructure.persistence.entity.mobile.MobileAppDOExample;

import java.util.List;

public interface MobileAppDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    long countByExample(MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int deleteByExample(MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int insert(MobileAppDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int insertSelective(MobileAppDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    List<MobileAppDO> selectByExampleWithBLOBs(MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    List<MobileAppDO> selectByExample(MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    MobileAppDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MobileAppDO row, @Param("example") MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") MobileAppDO row, @Param("example") MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MobileAppDO row, @Param("example") MobileAppDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MobileAppDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MobileAppDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MobileAppDO row);
}