package top.kx.heartbeat.infrastructure.persistence.mapper.mobile;

import org.apache.ibatis.annotations.Param;
import top.kx.heartbeat.infrastructure.persistence.entity.mobile.MobileAppVersionDO;
import top.kx.heartbeat.infrastructure.persistence.entity.mobile.MobileAppVersionDOExample;

import java.util.List;

public interface MobileAppVersionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    long countByExample(MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int deleteByExample(MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int insert(MobileAppVersionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int insertSelective(MobileAppVersionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    List<MobileAppVersionDO> selectByExampleWithBLOBs(MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    List<MobileAppVersionDO> selectByExample(MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    MobileAppVersionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MobileAppVersionDO row, @Param("example") MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") MobileAppVersionDO row, @Param("example") MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MobileAppVersionDO row, @Param("example") MobileAppVersionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MobileAppVersionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MobileAppVersionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_app_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MobileAppVersionDO row);
}